### PR TITLE
removed redundant code in factor graph unit test

### PR DESCRIPTION
**Pull request by Jiaolong**

### CODE REVIEW

**Comment by Jiaolong** [comment]
@hushell could you please help me to check this PR? The Travis error should not be related to my changes. This PR is part of the work for GEMPLP. Thanks!

**Comment by hushell** [comment]
@Jiaolong So the purpose of this is refactoring the unit-test code? It looks good at first scan. I'll check it more carefully later today.

**Comment by Jiaolong** [comment]
@iglesias the travis failed, could you please help me to check it? @hushell the MPLP code is ready for PR but this patch should be merged first. The current performance can be seen from
http://nbviewer.ipython.org/gist/Jiaolong/c25b694e3b0eb3093fac

**Comment by iglesias** [comment]
Never mind about the osx job, it has been broken for some time due to something unrelated. I have restarted the other two jobs since they failed due to compiler error (probably run out of memory, there may not work either next time).

**Comment by hushell** [comment]
@Jiaolong Sorry man! Deadlines and midterms ruined my plan. Didn't expect delaying your progress. I think your changes are good. I just need to double check it. I'll do it tomorrow night.

**Comment by hushell** [comment]
@Jiaolong I have gone through the code. It seems you just refactor the unit-test code, since many lines can be reused, am I right? If so, I am fine with your changes. Please double check valgrind to make sure no memory issues. Let's ask Fernando to get it merged.

**Comment by Jiaolong** [comment]
@hushell yes, you are totally right. I have already checked valgrind, no memory leaks.
@iglesias Could you help us to merge this patch? Thanks!

**Comment by hushell** [comment]
@Jiaolong Good job man! Looking forward to see your new MPLP code.

**Comment by Jiaolong** [comment]
@hushell Let's wait for the merge of this patch. I just pulled request of GEMPLP (#2706). You can check it if you have time.

**Comment by iglesias** [comment]
Thanks a lot for the patch @Jiaolong, and sorry for the wait.

**Comment by iglesias** [comment]
Via #2706.

**Pull request closed without merging**
