### PR TITLE
fix CARTree leaks

### LINKED ISSUE #4867: CARTree leaks
simply valgrind one of the metaexamples, i.e.:
```
valgrind --leak-check=full ./cpp-regression-cartree
```

### PR DESCRIPTION
**Pull request by LiuYuHui**
fix #4867

### CODE REVIEW

**Comment by gf712** [comment]
Thanks! Could you explain how this fixes the issue, please?

**Comment by LiuYuHui** [comment]
i think in TreeMachineNode.h line 122 `		child->parent(shared_from_this()->template as<TreeMachineNode<T>>());
` cause  cyclic references

**Comment by vigsterkr** [comment]
@LiuYuHui perfect! have you by any chance valgrind it? :)

**Comment by LiuYuHui** [comment]
yes, i valgrind it,  definitely lost is 0 bytes

**Comment by vigsterkr** [comment]
ok i let CI do it's job, but will merge as soon as its green

**Comment by gf712** [comment]
> i think in TreeMachineNode.h line 122 ` child->parent(shared_from_this()->template as<TreeMachineNode<T>>()); ` cause cyclic references

oh I see, makes sense!

**Pull request merged**
