### PR TITLE
replace CMath::swap with std::swap

### PR DESCRIPTION
**Pull request by Yashs744**
dropped CMath class function and added std function (#4186)

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks!
The build is failing due to style errors (you can click it to see the log)

https://travis-ci.org/shogun-toolbox/shogun/jobs/345852507#L729
Shows you how to fix it

**Comment by karlnapf** [comment]
LGTM
@vigsterkr ?

**Comment by karlnapf** [comment]
https://travis-ci.org/shogun-toolbox/shogun/jobs/346871904#L712
To fix the errors automatically please run: 
`git clang-format-3.8 --commit 36406d48ed0183b83c92c79285040322d00f69e6 --binary /usr/bin/clang-format-3.8`

**Comment by karlnapf** [comment]
This is good, just needs the correct style fix and we can merge it :)

**Comment by Yashs744** [comment]
Okay Sir, Thank you

**Comment by Yashs744** [comment]
Sir, I'm getting this error. I checked there is no conflict 
screenshot 36

**Comment by karlnapf** [comment]
You will need to read the git manual, or use google. Keywords "rebase" "merge conflict"

**Pull request merged**
