### PR TITLE
drop CMath::is_finite fix issue #4186

### PR DESCRIPTION
**Pull request by sunalbert**
replace CMath::is_finite with std::isfinite

### CODE REVIEW

**Comment by sunalbert** [comment]
How can I fix the errors? Thanks.

**Comment by grig-guz** [comment]
Try 8th point in https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/DEVELOPING.md

**Comment by sunalbert** [comment]
@grig-guz Thanks, I will have a try.

**Comment by karlnapf** [comment]
Doesnt compile with ruby.
Could you investigate a bit locally?

https://travis-ci.org/shogun-toolbox/shogun/jobs/358916322#L1677

**Pull request closed without merging**
