### PR TITLE
added convolution to linalg

### PR DESCRIPTION
**Pull request by khalednasr**
@lisitsyn, @vigsterkr Pushed #2418 again, this time against the develop branch instead of feature/linalg

### CODE REVIEW

**Comment by lambday** [comment]
@lisitsyn ping!

**Comment by lisitsyn** [comment]
Looks good - can we merge it?

**Comment by lambday** [comment]
@lisitsyn I think we can - its all new files except for Core.h.. not sure if we'll get merge conflicts. Can you merge this one?

**Comment by iglesias** [comment]
I will merge this one since you guys are good with it :-)

**Pull request merged**
