### PR TITLE
remove layers from swig

### PR DESCRIPTION
**Pull request by shubham808**

### CODE REVIEW

**Comment by karlnapf** [comment]
Nice, thanks!
As you can see, the CI is now [moaning](https://dev.azure.com/shogunml/shogun/_build/results?buildId=474&view=logs&jobId=089c709a-44eb-5f6e-96e7-15e9ee1ff5bf&taskId=5899c1e7-1112-57da-0a81-46bbe225a6c3&lineStart=127&lineEnd=128&colStart=1&colEnd=1) and you need to fix some examples

**Comment by karlnapf** [comment]
```
enum ENNOptimizationMethod
{
	NNOM_GRADIENT_DESCENT=0,
	NNOM_LBFGS=1
};
```
This is defined in `NeuralNetworks.h`, so you need to make sure SWIG sees this by either moving the enum to a file that is exposed to swig, or including the header within swig. I generally wonder whether we want neural networks as CMachine or as its own type?

**Comment by karlnapf** [comment]
The enum thing is a general problem that we are discussing how to solve atm, so don't spend too much time on it (for now just include the neural networks header and we can remove that later)

**Comment by shubham808** [comment]
This seems good to go now

**Comment by karlnapf** [comment]
Indeed! Nice
The notebooks need update as well. Do you mind updating them?

**Pull request merged**
