### PR TITLE
Updated KDE.ipynb

### PR DESCRIPTION
**Pull request by jonpsy**
@gf712, Updated KDE.ipynb , runs smoothly on conda package of shogun.

### CODE REVIEW

**Comment by gf712** [comment]
Oh, this is the opposite of what has to be done. You need to fix ipython notebooks to use the new API, this is reverting to the old API. To do this don't use conda, you need to build shogun from source using the develop branch and the run the notebooks with this!

**Comment by jonpsy** [comment]
Off to a good start!. So I should refactor the code such that, it works on the environment built from source?

**Comment by gf712** [comment]
> Off to a good start!. So I should refactor the code such that, it works on the environment built from source?

Haha, don't worry, I wasn't very clear. Yes, that's it. We try to keep the notebooks up to date when we refactor the API, but there might be some that aren't working!

**Comment by jonpsy** [comment]
Okay this should work when this #4951 is works for all platform

**Comment by gf712** [comment]
OK, but now nothing has changed in this notebook right?

**Comment by jonpsy** [comment]
Oh, yes! That's true!. Then this PR is for naught, it's all good.

Hmm...Shall I close it??

**Comment by gf712** [comment]
OK, closing this in that case

**Pull request closed without merging**
