### PR TITLE
Add meta example for hessian locally linear embedding converter.

### PR DESCRIPTION
**Pull request by Hephaestus12**

### CODE REVIEW

**Comment by gf712** [comment]
Did you add data files for these PRs?

**Comment by Hephaestus12** [comment]
> Did you add data files for these PRs?

No, I was waiting for approval regarding the meta example code. Should I go ahead with the datafiles?

**Comment by gf712** [comment]
I think it seems fine. Would be good to see if you still have issues with octave with other transformers

**Comment by geektoni** [comment]
The same issue with the integration test happens here.

**Pull request closed without merging**
