### PR TITLE
Port distance examples to meta examples

### PR DESCRIPTION
**Pull request by souravsingh**
Port the distance examples in Python to meta examples.

### CODE REVIEW

**Comment by karlnapf** [comment]
You got it! :) Very useful patch!
Can you send a patch with the integration testing data to the data repository, and then once merged, update the commit here with the data submodule version? So that travis executes the integration tests for your new examples

**Comment by souravsingh** [comment]
@karlnapf Sure, I will do it

**Comment by karlnapf** [comment]
Check the (compile) error: https://travis-ci.org/shogun-toolbox/shogun/jobs/180663257#L2350

This tells me that you didn't test the examples you wrote locally before you sent the PR. Please don't do this, it is a waste of CPU cycles in travis. Make sure to read our developing readme in the wiki.
It would be great if you could update the PR as we are very interested in having such examples in

**Comment by souravsingh** [comment]
It is taking me a long time to test the meta-examples in my local machine, which is why I had to skip the local testing.

**Comment by karlnapf** [comment]
It only takes very few seconds on mine (once shogun is compiled). Make sure to check the readme and find out how to run tests in an isolated way.

**Pull request closed without merging**
