### PR TITLE
Fixing incorrect usage of std::vector.reserve()

### PR DESCRIPTION
**Pull request by yozw**

### CODE REVIEW

**Comment by besser82** [comment]
Let's wait for Travis…  If things are fine there, I'll merge this.

**Comment by yozw** [comment]
Yep, sure! (3 times :) )

**Comment by karlnapf** [comment]
Please be very careful here as these changes are not covered by any tests that ensure invariant results. 

Why not quickly add a unit test?

Thanks ! :)

**Comment by besser82** [comment]
@karlnapf: No need for this…  Reserving memory directly upon initialization of the vector is covered by C++-standard.  The previous code created a vector, alloc'ed memory, free'ed the mem and realloc'ed memory of the needed size.

The change in here just creates a vector and directly alloc's the needed memory.

**Comment by karlnapf** [comment]
Ok then!
Good stuff

**Comment by besser82** [comment]
Allrighty!  Since Travis looks good for libshogun itself, things are safe here.  Merging…

@yozw: Many thanks for your contribution!  =)

**Pull request merged**
