### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### shogun-toolbox/shogun now has a Chat Room on Gitter

@vigsterkr has just created a chat room. You can visit it here: [https://gitter.im/shogun-toolbox/shogun](https://gitter.im/shogun-toolbox/shogun?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/shogun-toolbox/shogun?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by karlnapf** [comment]
Dont know about this....We have irc.
Also I dont like bot PRs...
what do you guys think?

**Comment by sanuj** [comment]
@karlnapf Gitter seems like a better chat client than the IRC we have :) I dunno about the bot PRs.
@iglesias ? @lisitsyn ? @besser82 ?

**Comment by lisitsyn** [comment]
I'm not sure Gitter is better. Such things are pretty temporary and when they are gone we have to move again. IRC is already older than me and I guess it would stay for a while :)

**Comment by karlnapf** [comment]
Let's stay with IRC then

**Pull request closed without merging**
