### PR TITLE
Replace cmath::sqrt with std::sqrt

### PR DESCRIPTION
**Pull request by grig-guz**
Fixed the  previous pull request

### CODE REVIEW

**Comment by vigsterkr** [comment]
@grig-guz great! there are still some formatting errors. you can fix those by using clang-format; for details check the 8th point in https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/DEVELOPING.md

**Comment by grig-guz** [comment]
@vigsterkr thanks! However, I'm not sure how to fix some of these errors. I ran the clang-format-3.8 as recommended by the script, but I still get errors like these 
error

**Comment by grig-guz** [comment]
The style check passed. Is it fine now?

**Comment by grig-guz** [comment]
Also, the formatting error detection script was inconsistent in some places. Sometimes, it required for line padding to only consist of tabs, and in other classes it was asking for tabs and 2-3 spaces.

**Comment by karlnapf** [comment]
Thx for the patch!

**Pull request merged**
