### PR TITLE
Added the links successfully

### PR DESCRIPTION
**Pull request by neeravjain24**
Here initially the link to INSTALL.md  was missing I added the link to INSTALL.md

### CODE REVIEW

**Comment by gf712** [comment]
i think this is already being done here #4859

**Comment by neeravjain24** [comment]
But I think its still broken .
On clicking on INSTALL.MD its still showing page not found.

**Comment by gf712** [comment]
you mean right now it's broken? that's because the PR has not been merged yet

**Comment by neeravjain24** [comment]
Yes I meant right now BTW thanks for letting me know .

**Comment by iglesias** [comment]
Thanks for fixing.

**Pull request merged**
