### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by nouranali**

### CODE REVIEW

**Comment by nouranali** [comment]
@gf712

**Comment by nouranali** [comment]
@karlnapf

**Review by karlnapf — APPROVED** [review]
@gf712 can merge

**Comment by gf712** [comment]
Thanks! In future could you put all these one liners in a single PR though? Each time you are triggering the CI which uses up a lot of resources that other contributors could be using.

**Comment by nouranali** [comment]
> Thanks! In future could you put all these one liners in a single PR though? Each time you are triggering the CI which uses up a lot of resources that other contributors could be using.

Okay I will, thanks for the advice

**Pull request merged**
