### PR TITLE
Remove apply_locked* methods from SWIG interfaces #3687

### PR DESCRIPTION
**Pull request by tdjogi010**

### CODE REVIEW

**Comment by karlnapf** [comment]
All this should be done in `CMachine.h`

Also, `virtual bool train_locked(SGVector<index_t> indices)` should also be guarded

**Comment by tdjogi010** [comment]
@karlnapf what about the apply_lock* methods in other classes(like CKernelMachine, CDirectorKernelMachine,etc)? Should they not be guarded as well? (or is it because they are not included in swig interfaces already since -fvirtual is used with swig?)

**Comment by karlnapf** [comment]
I actually don't know. Would be good to check this out....

**Comment by karlnapf** [comment]
Thanks for the patch!
For the record, I checked the IPython notebooks, and none of them use the methods, so merging

**Comment by tdjogi010** [comment]
Thanks!

**Pull request merged**
