### PR TITLE
Updated naive bayers classifier

### PR DESCRIPTION
**Pull request by Dynamo13**
Used pandas to import dataset sklearn for preprocessing  and confusion matrix to check accuracy. The classifier is GaussianNB( lines 23-26)

### CODE REVIEW

**Comment by karlnapf** [comment]
It just keeps coming....

**Comment by Dynamo13** [comment]
Well I need to know where I am going wrong!

**Comment by geektoni** [comment]
@Dynamo13 the problem here is that you are not addressing any particular Shogun issue. You are just adding random code in the wrong places. If you want to work on examples, then you should have a look at our cookbook system and go from there (#3555). If you want to work on other issues, just go through our "Issue" list here on Github. Please also make sure to read our Wiki's guide about how to contribute to the project itself.

**Comment by vigsterkr** [comment]
@Dynamo13 i have written you explicitly here what you are doing wrong: https://github.com/shogun-toolbox/shogun/pull/4966#issuecomment-605015217

this is the very last time.... the next time i'll have to report you as a spammer on github.

**Comment by vigsterkr** [comment]
> Well I need to know where I am going wrong!

do you really think this is the appropriate way to move forward when people are closing your PRs right away and telling you what you should consider doing? you just ignore the requests and keep on doing it...

**Comment by karlnapf** [comment]
I don’t think there is any point replying to this as this is likely a group of people trying to mass spam their way into gsoc. There were reports of this at the mailing list at some point.

**Pull request closed without merging**
