### PR TITLE
Added cmake switch to enable/disable eigen3/viennacl

### PR DESCRIPTION
**Pull request by lambday**
@lisitsyn @vigsterkr @karlnapf please have a look :)

### CODE REVIEW

**Comment by karlnapf** [comment]
If you grep'ed for all of those, then fine to merge from my side

**Comment by lambday** [comment]
@karlnapf i am afraid that grepping won't help here because we have these `HAVE_EIGEN3` and `HAVE_VIENNACL` macros all over the place. The `ENABLE_EIGEN` and `ENABLE_VIENNACL` macros are not being defined in any c header (cmake internal). But from my local run it seems to work
```
[lambday@lambday.iitb.ac.in build]$ rm -rf * && cmake -DENABLE_EIGEN=OFF -DENABLE_VIENNACL=OFF -DENABLE_TESTING=ON ..
-- The C compiler identification is GNU 4.9.2
.
.
.
-- Supported backend(s) for linear algebra NOT FOUND/NOT ENABLED
.
.
.
===================================================================================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lambday/Downloads/shogun/build
```

**Comment by lambday** [comment]
@karlnapf merging this one. Working fine locally.

**Comment by karlnapf** [comment]
@lambday yeah sure. I meant in the CMakeLists.txt.
Cool to have this now! :)

**Pull request merged**
