### PR TITLE
Removed unused template parameter from CLinearOperator

### PR DESCRIPTION
**Pull request by lambday**
- CLinearOperator has only one template parameter now
   since the other template parameter is not used anywhere.

### CODE REVIEW

**Comment by lambday** [comment]
@karlnapf @iglesias @lisitsyn I am planning to make some changes aimed at reducing compilation time. This was on my list for a long time.

**Comment by lisitsyn** [comment]
@lambday does that speed up the compilation?

**Comment by lambday** [comment]
@lisitsyn it's a start.. Removing unused things that unnecessarily takes up compiler's time could be useful at least. Next patches would include usage of pimpl and getting rid of all _but_ mandatory header inclusions in the .h files and relying on forward declaration in most of the cases.

**Comment by iglesias** [comment]
lgtm :+1:

**Comment by lambday** [comment]
Alright. Travis errors seem unrelated. Merging this one.

**Pull request merged**
