### PR TITLE
using factory methods in kernel ridge regression meta example

### PR DESCRIPTION
**Pull request by shubham808**

### CODE REVIEW

**Comment by karlnapf** [comment]
Can be merged once CI is green

**Comment by shubham808** [comment]
yes sure :)

**Comment by karlnapf** [comment]
You need to make sure the meta example compiles in cpp when you change things:
https://travis-ci.org/shogun-toolbox/shogun/jobs/382677577#L3451

This can be solved via replacing the assertion for regression labels with a conversion that uses `regression_labels` (see my PRs where I did this for some other classes)

**Comment by shubham808** [comment]
yeah i did miss the conversion.... i have updated this now

**Pull request merged**
