### PR TITLE
Fix a few links in the notebook

### PR DESCRIPTION
**Pull request by souravsingh**
Related to #3522

### CODE REVIEW

**Comment by karlnapf** [comment]
See my updated description in the issue.
This needs to be applied to all notebooks.....

**Comment by karlnapf** [comment]
Thanks! This is good. But can you fix all links?
The String features ones also appear to be broken.

**Comment by karlnapf** [comment]
We'll fix the other ones differently. Thanks for this

**Comment by souravsingh** [comment]
Thanks for merging the PR @karlnapf. I would like to finish up fixing the rest of the notebooks.

**Comment by karlnapf** [comment]
the opencv one is the only one failing for now I think, this is due to an API change arising from re-structuring the opencv codebase....

**Pull request merged**
