### PR TITLE
separate classifiers in cookbook

### PR DESCRIPTION
**Pull request by OXPHOS**

### CODE REVIEW

**Comment by OXPHOS** [comment]
shogun-data may also need updates

**Comment by karlnapf** [comment]
It does! And it does need so first, and then the data version in here needs to be updated.
But all good otherwise and thanks!

**Comment by karlnapf** [comment]
Can you bump up the data revision, then we can test this....

**Comment by OXPHOS** [comment]
@karlnapf data tests passed - ready

**Comment by karlnapf** [comment]
Merge conflict.
This is since I merged other cookbooks in the meantime.
You have to rebase, sorry.

**Comment by OXPHOS** [comment]
@karlnapf  rebased

**Comment by karlnapf** [comment]
Ok merging as travis was green before

**Comment by karlnapf** [comment]
@OXPHOS please have a close eye on travis and the buildbot. Ping me asap if something broke

**Comment by OXPHOS** [comment]
@karlnapf They're interrupted!

**Comment by karlnapf** [comment]
restarted some

**Pull request merged**
