### PR TITLE
remove TRACE_MEMORY_ALLOCS

### PR DESCRIPTION
**Pull request by gf712**
removed TRACE_MEMORY_ALLOCS from everywhere

### CODE REVIEW

**Comment by karlnapf** [comment]
Lol did this compile before?

**Comment by vigsterkr** [comment]
@karlnapf afaik we never relied on this feature...

**Comment by gf712** [comment]
Yea caused an issues in one of the buildbot jobs

**Comment by karlnapf** [comment]
Maybe just remove it? I used it a few ones years ago but these days valgrind offers all those features (linenof allocation etc)

**Comment by gf712** [comment]
yup can do that!

**Pull request merged**
