### PR TITLE
replace lapack calls

### PR DESCRIPTION
**Pull request by Saurabh7**

### CODE REVIEW

**Comment by vigsterkr** [comment]
perfect! let's see what travis says... and then merge

**Comment by karlnapf** [comment]
Covered by unit test this one?
Otherwise fine to merge

**Comment by Saurabh7** [comment]
No test atm. I can add a comparison. Should I push the test here or another PR to merge before?

**Comment by Saurabh7** [comment]
I have added it here: https://github.com/shogun-toolbox/shogun/pull/3290

**Comment by vigsterkr** [comment]
@Saurabh7 move it to here plz!

**Comment by karlnapf** [comment]
This is all green already, so could merge. But waiting for adding the other test

**Comment by vigsterkr** [comment]
@Saurabh7 waiting for the test to be added here....

**Comment by Saurabh7** [comment]
Ok done , also replaced a  single linalg call to avoid guarding it.

**Pull request merged**
