### PR TITLE
update docker config to install matplotlib

### PR DESCRIPTION
**Pull request by sanuj**
Installs matplotlib in travis docker builds. For #3146

### CODE REVIEW

**Comment by karlnapf** [comment]
@vigsterkr you ok with that? I am

**Comment by vigsterkr** [comment]
@sanuj @karlnapf is this for graphical examples?
we really want them to be run as tests?

**Comment by karlnapf** [comment]
@vigsterkr the idea was mostly to check basic things such as imports, method names etc. So in a way, yes. But just executing, not asserting results. The problem currently is that they outdated (as in not executable) over time, and it takes time to fix.

**Comment by vigsterkr** [comment]
i mean it's just a docker image and it will not hurt anybody to have matplotlib in the container :)

**Pull request merged**
