### PR TITLE
Add ManhattanWordDistance meta example

### PR DESCRIPTION
**Pull request by braceletboy**
Changes to be committed:
	new file:   examples/meta/src/distance/manhattan_word.sg.in
	deleted:    examples/undocumented/python/distance_manhattanword.py

### CODE REVIEW

**Comment by braceletboy** [comment]
#3555 
Hi,
This is my first time writing a meta example.
Can anyone review this PR and provide me with feedback?

**Comment by LiuYuHui** [comment]
Hi @braceletboy, thanks for your pr, could you also add the data files please?

**Comment by braceletboy** [comment]
@LiuYuHui I used data files that were already present in the shogun-data repository. You can find them here: [train](https://github.com/shogun-toolbox/shogun-data/blob/master/toy/fm_train_dna.dat) and [test](https://github.com/shogun-toolbox/shogun-data/blob/master/toy/fm_test_dna.dat)

**Comment by LiuYuHui** [comment]
Hi @braceletboy, when you port a new meta example, it will produce a new data file, please check this [link](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/EXAMPLES.md#adding-new-examples), if you are porting a new example, please also add the produced datafile so that we can do integration tests automatically, thanks.

**Comment by braceletboy** [comment]
@LiuYuHui When I tested and ran the examples locally, it didn't produce a new data file. I did refer to the link you pointed out while I was writing the new example file. I even ran tests on the examples that I created using `ctest -R manhattan_word*` and all the tests passed.

**Comment by LiuYuHui** [comment]
@braceletboy you can the produced data file in `build/examples/meta/cpp/distance`.

**Comment by braceletboy** [comment]
Okay. Thanks @LiuYuHui 
Found the datafile. I have a question though. It seems that latest commit in `shogun-data` is not being tracked by the `shogun` repository. Is it alright to just commit and push changes to shogun-data or should I make a commit in shogun as well (so that it tracks the latest changes)? Following is a screenshot of `git diff data/` (after did a `git checkout master` inside the data folder)
image

**Comment by LiuYuHui** [comment]
you should first make pr to shogun-data, and then updata the commit to shogun.

**Comment by LiuYuHui** [comment]
Hi @braceletboy, it seems like that you didn't update your commit to shogun-data, please follow those steps:
```
cd shogun/data && git remote add mydata <your data repo>
git fetch mydata
```
then push this commit to shogun.

**Comment by braceletboy** [comment]
@LiuYuHui  I added the commit I made to shogun-data and all checks are failing. I am not entirely sure what is happening. I am a bit new to using submodules - so please bear with me (thanks). I did the following:
```
cd shogun/data && git remote add mydata <your data repo>
git fetch mydata
git cherry-pick 68272c53186800d18ea7fb57469a4baab3d152ca
git add data/
git commit
git push origin add_meta_examples
```
`68272` is the commit that I raised a PR for in shogun-data

**Comment by braceletboy** [comment]
@LiuYuHui Is this okay?

**Comment by LiuYuHui** [comment]
Hi @braceletboy, after 
```
cd shogun/data && git remote add mydata <your data repo>
git fetch mydata
``` 
you should checkout your branch in shogun/data
```
git checkout add_meta_examples
```

**Comment by braceletboy** [comment]
@LiuYuHui  I have done as you have suggested. Also, is there a reason for the swig interface related shogun-ci failing?

**Comment by gf712** [comment]
> @LiuYuHui I have done as you have suggested. Also, is there a reason for the swig interface related shogun-ci failing?

Hi, there is an issue with the building of the interfaces atm. The issues you are seeing here are probably related to that.

**Pull request closed without merging**
