### PR TITLE
change the license

### PR DESCRIPTION
**Pull request by yorkerlin**
@karlnapf

### CODE REVIEW

**Comment by lisitsyn** [comment]
Tricky! :)

Are all authors agree about license change?

**Comment by yorkerlin** [comment]
@lisitsyn 
yes. 
Roman agreed about the license change when I worked in GSoC 2014.
Last week, I asked Jacob about the change and he agreed.

**Comment by yorkerlin** [comment]
@lisitsyn , @karlnapf 
Since all related authors agree to change the license, I merge this.

**Comment by karlnapf** [comment]
Thanks!

**Pull request merged**
