### PR TITLE
fix a bug in CombinedKernel

### PR DESCRIPTION
**Pull request by yorkerlin**
@karlnapf  @vigsterkr

### CODE REVIEW

**Comment by yorkerlin** [comment]
Let's wait until travis is green.

**Comment by yorkerlin** [comment]
@karlnapf  @vigsterkr 
Any idea why the unit tests in travis are failed?

**Comment by karlnapf** [comment]
Thanks!
Hey, could you please start writing informative commit messages?
"Fix a bug" is a no go as not helpful at all

**Comment by yorkerlin** [comment]
Will write informative commit messages from now on. :)

**Comment by karlnapf** [comment]
Thanks :)

**Pull request merged**
