### PR TITLE
Fix broken LDA unit test

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/shogun-toolbox/shogun/issues/3107

### CODE REVIEW

**Comment by karlnapf** [comment]
This is not a fix

**Comment by karlnapf** [comment]
I will merge as this test is broken
@OXPHOS  if you rebase, then your linalg patch should work

**Comment by theaverageguy** [comment]
Could you help me with this @karlnapf ? 
I believe I didn't understand it properly. The link you shared did disable the class.

**Comment by karlnapf** [comment]
Sure, it is now disabled. Better would be to *fix* the test and activate it again. Next step. Find out why it failed in the first place.

**Pull request merged**
