### PR TITLE
FITC methods are included in the BSD-only Shogun

### PR DESCRIPTION
**Pull request by yorkerlin**
@karlnapf

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks for cleaning this up.
NOTE: travis currently does not cover the BSD build. You will have to test this by hand.
@vigsterkr can we add a USE_GPL_SHOGUN=OFF build to travis? Or at least the buildbot (more important)

**Comment by karlnapf** [comment]
@yorkerlin feel free to merge this *if tested locally*

**Comment by yorkerlin** [comment]
all related unit tests are passed.
merging

**Comment by karlnapf** [comment]
Great.
Please keep an eye on both the buildbot and the local build with USE_GPL_SHOGUN set to ON and to OFF

**Pull request merged**
