### PR TITLE
updated ABOUT.md

### PR DESCRIPTION
**Pull request by nouranali**
fixed a phrase

### CODE REVIEW

**Comment by nouranali** [comment]
Okay, @gf712 I'm so sick of this error, I rebased and everything but still getting some checks were not successful, help :'(

**Comment by gf712** [comment]
> Okay, @gf712 I'm so sick of this error, I rebased and everything but still getting some checks were not successful, help :'(

Which error?

**Comment by nouranali** [comment]
> > Okay, @gf712 I'm so sick of this error, I rebased and everything but still getting some checks were not successful, help :'(
> 
> Which error?

"Some checks were not successful"

**Comment by gf712** [comment]
oh don't worry about that, that is not because of your PR

**Comment by nouranali** [comment]
> oh don't worry about that, that is not because of your PR
Really :'( okay then,
how can I merge when it's not passing the checks?

**Comment by gf712** [comment]
Well, you can’t merge.. only a shogun member can merge

**Comment by nouranali** [comment]
> Well, you can’t merge.. only a shogun member can merge

okay

**Comment by nouranali** [comment]
I created a NOTEBOOKS.md as mentioned in issue #3519 perhaps you could help me get started 
@gf712

**Comment by karlnapf** [comment]
this PR contains parts of other PRs you have sent before (opencv readme). It is fine if you want to group things, but it would be good if you closed the other PR (or better, not open it in the first place).

Went through the suggested changes here and don't think they are improving things. See my other comment on the docstrings as a suggestion what to get involved with.

**Pull request closed without merging**
