### PR TITLE
a new features class

### PR DESCRIPTION
**Pull request by yorkerlin**
@karlnapf

### CODE REVIEW

**Comment by yorkerlin** [comment]
ref:
https://github.com/shogun-toolbox/shogun/issues/2857

**Comment by karlnapf** [comment]
Again the question why we cannot just use the subset feature of DenseFeatures and just create a convenience class here?

**Comment by yorkerlin** [comment]
@karlnapf 
The `DenseSubSamplesFeatures` class wraps `DenseFeatures` and the indices of a subset.
I think this class is the `convenience` class you mentioned.

There are reasons why the `DenseSubSamplesFeatures` class.
* memory efficiency  
** we do `not` need to copy the subset to create a new `DenseFeatures` class
* API design
```
class StochasticGPInference(CFeatures *) 
{
protected:
Minimizer* m_opt
};

class StreamingGPInference: public StochasticGPInference
{
}

class BatchGPInference(CFeatures *) : public StochasticGPInference
{
protected:
Scheduler* m_sch // generate indices of  a mini-batch to create DenseSubSamplesFeatures
}
```
 
Let me know your suggestions?

**Comment by karlnapf** [comment]
No I agree then! Good!

**Pull request merged**
