### PR TITLE
Move multitask clustered LR to gpl directory

### PR DESCRIPTION
**Pull request by lisitsyn**

### CODE REVIEW

**Comment by karlnapf** [comment]
#3786

**Comment by karlnapf** [comment]
cah

**Comment by iglesias** [comment]
Should the example python_modular/transfer_multitask_clustered_logistic_regression.py also moved under gpl?

**Comment by karlnapf** [comment]
Thanks for noting that!
Nope, that code (the example itself) is not GPL (I mean it is but we can change that). This example should be guarded in the build instead.

**Pull request merged**
