### PR TITLE
clean up regression notebook

### PR DESCRIPTION
**Pull request by sanuj**
Removes a deprecated warning and three errors. This notebook has been saved for version 4 of ipython since i have that installed on my laptop.

@karlnapf I wanted to confirm whether version 4 is ok for shogun or should i stick to version 3 (that shogun uses currently) before I send anymore notebook related PRs.

### CODE REVIEW

**Comment by sanuj** [comment]
Got [this error](https://gist.github.com/sanuj/fb788cbbd819eb6c2cfe) at 3 different places. The fix was to make `c` take an array whose length was equal to number of training points that were being plotted.

Also `changed set_color_cycle` to `set_prop_cycle` to fix the following deprecated warning.
```
/usr/local/lib/python2.7/dist-packages/matplotlib/cbook.py:137: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
```

The notebook is rendered weirdly on Github. It looks fine when I run it locally.

**Comment by karlnapf** [comment]
@vigsterkr what ipython is on the buildbot?

**Comment by vigsterkr** [comment]
```3.1.0```

**Comment by karlnapf** [comment]
If we have the new version (which we should) I am up for merging this....

**Comment by karlnapf** [comment]
can update?

**Comment by vigsterkr** [comment]
yes

**Comment by sanuj** [comment]
[Info about latest IPython version.](http://ipython.org/news.html)

**Comment by vigsterkr** [comment]
so we want 4.x?

**Comment by vigsterkr** [comment]
just upgraded to `ipython (4.1.2)`

**Comment by karlnapf** [comment]
Nice thanks, I will merge

**Pull request merged**
