### PR TITLE
build: Describe method for downloading GPL codes in build error message

### PR DESCRIPTION
**Pull request by samdbrice**

### CODE REVIEW

**Comment by samdbrice** [comment]
Need to fix the

**Comment by samdbrice** [comment]
Not sure what's causing the FOLDING_EXPRESSIONS failure

**Comment by gf712** [comment]
That’s an error you get when the compiler doesn’t support c++17 fold expressions

**Comment by karlnapf** [comment]
only the CI needs to pass, dont worry about the buildbot atm.

If you think this is a better error msg, happy to merge it. From my perspective, there is not more information and I am always sceptical of quoting things like git commands as that leads to redundancy and it is hard to maintain (things tend to change). However, you have a better "outside" perspective :) so let's do it

**Comment by samdbrice** [comment]
Sounds good to me. Feel free to merge this.

**Pull request merged**
