### PR TITLE
fixed a memory leak bug

### PR DESCRIPTION
**Pull request by yorkerlin**

### CODE REVIEW

**Comment by yorkerlin** [comment]
@karlnapf 
We should use c++11 soon.
The main reason of this issue is the `optimization` is not a `SGObject.`

**Comment by yorkerlin** [comment]
One issue about changing Minimizer as a sub-class of SGObject:
Some minimizer uses some external lib (eg, LBFGS, and NLOPT) and some type from the external lib.
It seems to be hard to serialize this external type.  (eg, https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/optimization/NLOPTMinimizer.h#L128) 
Any idea about this issue? @vigsterkr  @lisitsyn  @lambday

**Comment by karlnapf** [comment]
Make it a sub-class then....As I said, the motivation to not do this earlier is not existing anymore.

**Comment by karlnapf** [comment]
If you just dont do SG_ADD, then varialbes will be ignored when serializing.....

**Comment by yorkerlin** [comment]
I close this due to https://github.com/shogun-toolbox/shogun/pull/3380

**Pull request closed without merging**
