### PR TITLE
Remove SGVector::fequal

### PR DESCRIPTION
**Pull request by sanuj**
@iglesias Please review.

### CODE REVIEW

**Comment by iglesias** [comment]
Did you check for uses of it in modular examples and notebooks? Note that SGVector changes name in modular interfaces so grep for fequal, .fequal, or so, rather than for SGVector::fequal.

**Comment by sanuj** [comment]
Yes I did. Only `fequal` from `CMath` is being used everywhere. If  that would have been the case then I would have got some error while building and testing on my machine. But it compiled properly and all the test cases also ran successfully.

**Comment by iglesias** [comment]
There would have not necessarily been an error if it were used in the notebooks and (maybe) part of the examples (e.g. graphical ones?) as they are not covered by tests.

**Comment by sanuj** [comment]
@iglesias Oh, alright! Thanks :)

**Pull request merged**
