### PR TITLE
fix integration testing path

### PR DESCRIPTION
**Pull request by gf712**

### CODE REVIEW

**Comment by vigsterkr** [comment]
oh ok! btw you've managed to fix the notebook job! \o/

**Comment by vigsterkr** [comment]
and i'm guessing the multiclass-cartree integration test fails because of this: https://github.com/shogun-toolbox/shogun/pull/4869/files#diff-66eff816d6c5ba765a04c543b4301daaR31

@LiuYuHui do you think you wanna create a patch (this is a good exercise how to update integration test/shogun-data repository) to fix the error in the integration test?

**Comment by gf712** [comment]
> oh ok! btw you've managed to fix the notebook job! \o/

Next one, cookbook.. Btw notebooks should be failing no?

**Comment by LiuYuHui** [comment]
> 
> 
> and i'm guessing the multiclass-cartree integration test fails because of this: https://github.com/shogun-toolbox/shogun/pull/4869/files#diff-66eff816d6c5ba765a04c543b4301daaR31
> 
> @LiuYuHui do you think you wanna create a patch (this is a good exercise how to update integration test/shogun-data repository) to fix the error in the integration test?

ok, first sending a PR against the shogun-data, and sending a PR to shogun?

**Comment by vigsterkr** [comment]
@LiuYuHui yes basically that's the idea

**Pull request merged**
