### PR TITLE
Cereal serialization - Enable SGMatrix serialization in SGObject

### PR DESCRIPTION
**Pull request by OXPHOS**
It looks kinda ugly with all these data types listed explicitly...

### CODE REVIEW

**Comment by OXPHOS** [comment]
@vigsterkr wanna check this one?

**Comment by vigsterkr** [comment]
@OXPHOS mmmm it's just waaaaaaaaaaaaay toooo verbose... template to the rescue?

**Comment by OXPHOS** [comment]
@vigsterkr The type information is completely removed and I didn't find a way to completely avoid listing... One way is using `enum Type {  INT8, SGVECTOR_INT8, SGMATRIX_INT8 .. }`, the other one is to use Macros, but neither will improve much.

**Comment by OXPHOS** [comment]
@vigsterkr have any good idea? I don't think template could do much

**Comment by karlnapf** [comment]
@OXPHOS hi there! Let's get this merged ! :)
So I guess we can avoid all this duplicate code with defining some macros no?
However, I dont think we can get around explicitly listing all these cases (unfortunately) we had this problem before ...
It is not very nice, but I am fine to merge this stuff anyways -- can discuss in IRC.

**Comment by OXPHOS** [comment]
Okay I am back to this.

**Comment by karlnapf** [comment]
Let's get this in! :)

**Comment by karlnapf** [comment]
Rebase and merge? :)

**Comment by gf712** [comment]
@vigsterkr your serialisation stuff does this right?

**Comment by vigsterkr** [comment]
yep this is all fixed

**Pull request closed without merging**
