### PR TITLE
minor fixes HAVE_LINALG

### PR DESCRIPTION
**Pull request by Saurabh7**
some fixes after https://github.com/shogun-toolbox/shogun/pull/3042.

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks!

**Comment by Saurabh7** [comment]
Hmm I didnt know about this HAVE_LINALG change  @karlnapf 
https://github.com/shogun-toolbox/shogun/commit/7339764920061d35581287f2483c24cc6187901e#diff-af3b638bc2a3e6c650974192a53c7291L760
 so its set to 1 only if VIENNACL is found ??

**Comment by karlnapf** [comment]
Yes, we recently made eigen3 a hard requirement

**Comment by Saurabh7** [comment]
ah then this guard wouldnt make sense here, it will fail even if eigen is found ?

**Comment by karlnapf** [comment]
HAVE_LINALG is only set if c++11 is available, that is why you need to use it

**Pull request merged**
