### PR TITLE
Cereal-rebase

### PR DESCRIPTION
**Pull request by OXPHOS**

### CODE REVIEW

**Comment by vigsterkr** [comment]
@OXPHOS i'm just updating the travis build image so that you have libcereal-dev available :) once it's done i'll let you know

**Comment by vigsterkr** [comment]
although yeah including cereal in .h is not the best thing :P

**Comment by vigsterkr** [comment]
@OXPHOS could you fix the clang-format errors? btw do we wanna merge this directly into develop now?

**Comment by OXPHOS** [comment]
@vigsterkr Thanks! I am trying to rebase the origin `feature/cereal` branch on `develop`. But it was kinda tricky so I want to make sure all tests passed first. I'll close this PR w/o merging when they're all green..

**Comment by vigsterkr** [comment]
@OXPHOS cool still formatting issues :)

**Comment by vigsterkr** [comment]
but i dont care... so use this to forcepush the feature branch...

**Comment by OXPHOS** [comment]
`Any.h` format check failed

**Comment by karlnapf** [comment]
@OXPHOS Can you write me an email once this kinda works?

**Comment by OXPHOS** [comment]
Force pushed to `feature/cereal`

**Pull request closed without merging**
