### PR TITLE
Rename 'modshogun' to 'shogun'

### PR DESCRIPTION
**Pull request by lisitsyn**

### CODE REVIEW

**Comment by karlnapf** [comment]
https://travis-ci.org/shogun-toolbox/shogun/jobs/249789498#L3545

**Comment by lisitsyn** [comment]
I don't get it yet

**Comment by lisitsyn** [comment]
@karlnapf ready to go. It is a major change so please take a look.

**Comment by lisitsyn** [comment]
`shogun.Classifier` etc stops working once merged.

**Comment by vigsterkr** [comment]
@lisitsyn we kind of deprecated that already a longer time ago :D (submodules)

**Comment by vigsterkr** [comment]
@lisitsyn although i dont get why, i mean both in case of python as well as in case of java it'd be great to have a module for `classifier` etc. no?

**Comment by lisitsyn** [comment]
@vigsterkr yeah namespaces are good but IIRC in the end they were too intertwined.

**Comment by vigsterkr** [comment]
@lisitsyn but that's rather because we are not clear on that internally... or you reckon it's unavoidable..?

**Comment by lisitsyn** [comment]
Yeah too many dependencies to have separate modules so we gave up :)

**Comment by lisitsyn** [comment]
YOLO!

**Pull request merged**
