### PR TITLE
clean up memcpy in swig typemaps

### PR DESCRIPTION
**Pull request by MikeLing**
#3700 #3724

### CODE REVIEW

**Comment by lambday** [comment]
@vigsterkr The VS15 cmake can't detect compilers?

**Comment by vigsterkr** [comment]
@lambday just ignore the error... it's already fixed.

**Comment by lambday** [comment]
Okay. Merging this then.

**Comment by lambday** [comment]
Thanks @MikeLing

**Comment by vigsterkr** [comment]
@lambday ah and just for the record... there's no swig interface compilation being done on windows :)

**Comment by lambday** [comment]
@vigsterkr your baby ruling all over Shogun now :D

**Comment by lambday** [comment]
errr... you mean only on the CI or it simply cannot build anything other than libshogun?

**Comment by vigsterkr** [comment]
CI obviously :) but yeah i never ever tried building swig interfaces with MSVC.... and i would be a bit surprise if somebody ever did it... although would be cool :)

**Pull request merged**
