### PR TITLE
Added maybe - a holder for potentially absent values

### PR DESCRIPTION
**Pull request by lisitsyn**
Work in progress but please comment

### CODE REVIEW

**Comment by karlnapf** [comment]
Out of my competence scope. Can you explain a bit or point to references?

**Comment by lisitsyn** [comment]
@karlnapf it is useful if a function sometimes can not return anything. If you use pointer semantics absent value is nullptr but in case of value semantics one better use optional/maybe

**Comment by karlnapf** [comment]
I see. We want this to make code look nicer?
I don't see the different between ```NULL->method()``` and an error caused by absent value apart from cosmetics? Or do I miss something?

**Comment by lisitsyn** [comment]
@karlnapf yes that's safer and it has value semantics instead of pointer semantics

**Comment by karlnapf** [comment]
safer in the sense that we dont cause segfaults or read uninitialised memory? Nicer because no pointer semantics?

Cool I get it then.

**Comment by lisitsyn** [comment]
Just pushed reworked Maybe

**Comment by vigsterkr** [comment]
:two_hearts:

**Comment by lisitsyn** [comment]
Travis errors unrelated (gosh we have to fix travis), merging

**Pull request merged**
