### PR TITLE
added confidences to neural networks output

### PR DESCRIPTION
**Pull request by khalednasr**
addresses #2758

### CODE REVIEW

**Comment by lisitsyn** [comment]
Wow welcome back ;)

**Comment by khalednasr** [comment]
@lisitsyn Thanks :)

**Comment by karlnapf** [comment]
Welcome :)

**Comment by lisitsyn** [comment]
Could you please add confidences for binary classification as well?

**Comment by khalednasr** [comment]
@karlnapf Thanks :)

@lisitsyn Forgot about those :) added them now.

**Comment by lisitsyn** [comment]
Thanks @khalednasr !

**Pull request merged**
