### PR TITLE
[PrematureStopping] Refactor CSignal class to use RxCpp utilities.

### PR DESCRIPTION
**Pull request by geektoni**
This PR <del>should</del> contains the new `CSignal` implementation which will be using RxCpp. <del>However, there are still some things that needs to be addressed (`CSignal::cancel_computation`, there is still Windows code etc.).</del>

### CODE REVIEW

**Comment by karlnapf** [comment]
@geektoni can you write down a simple use case from an algorithm implementation perspective? Thx

**Comment by geektoni** [comment]
@karlnapf Do you mean how this new CSignal will be used?

**Comment by geektoni** [comment]
@karlnapf I made a small code and output example to show the basic behavior that CSignal will allow: https://gist.github.com/geektoni/1afd2daf69a813de64252a296997a8ea

**Comment by vigsterkr** [comment]
```	148 - unit-Signal (OTHER_FAULT)```

**Comment by vigsterkr** [comment]
a bit of a more information
```
Note: Google Test filter = Signal.*

[==========] Running 2 tests from 1 test case.

[----------] Global test environment set-up.

[----------] 2 tests from Signal

[ RUN      ] Signal.SIGINT_test

/opt/shogun/tests/unit/lib/Signal_unittest.cc:26: Failure

Death test: { CSignal tmp; tmp.enable_handler(); int on_next_v = 0; int on_complete_v = 0; auto sub = rxcpp::make_subscriber<int>( [&on_next_v](int v) { on_next_v = 1; }, [&]() { on_complete_v = 1; }); tmp.get_SIGINT_observable().subscribe(sub); tmp.get_SIGINT_observable().connect(); switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar_ = ::testing::AssertionResult((on_complete_v == 1))) ; else ::testing::internal::AssertHelper(::testing::TestPartResult::kNonFatalFailure, "/opt/shogun/tests/unit/lib/Signal_unittest.cc", 26, ::testing::internal::GetBoolAssertionFailureMessage( gtest_ar_, "on_complete_v == 1", "false", "true").c_str()) = ::testing::Message(); exit(0); }

    Result: died but not with expected exit code:

            Terminated by signal 6 (core dumped)

Actual msg:

[  DEATH   ] terminate called without an active exception

[  DEATH   ] 

[  FAILED  ] Signal.SIGINT_test (286 ms)

[ RUN      ] Signal.SIGURG_test

terminate called without an active exception```

**Pull request merged**
