### PR TITLE
Helps in fixing #4817

### PR DESCRIPTION
**Pull request by naruarjun**
Helps in Fixing #4817

This adds the functionality to print entire code from a file generated by a metaexample, I have tested it and rendered cookbooks and it works well.

The command to be added to .rst files is 
```.. sgexample:: filename.sg:entire```

I will create a python script to add this to each file if this is merged.

### CODE REVIEW

**Comment by vigsterkr** [comment]
why do we need to change the rst file? you could just create in sphinx a thing to read in the whole file remove the comments and show the listing... i'm not so sure why it's required to extend the rst

**Comment by naruarjun** [comment]
So I thought this would help us to keep it uniform, I will create a python script that creates a new rst file for each existing rst file and add this line to the new rst file, Then create a hyperlink button, so the user could view the final code in all languages.

**Comment by naruarjun** [comment]
The existing files are not modified.

**Comment by naruarjun** [comment]
Since a hyperlink is to be created, I thought easiest and hassle free way to display the code in a new page was this.

**Comment by vigsterkr** [comment]
i dont see really the point... this could be a simple jquery script that basically loads in the listing and just shows it.... and no please no new page, that's super clunky UX wise

**Comment by naruarjun** [comment]
Ok, I'll look into that approach.
I thought a new page because in the issue it said to add a show full listing button and when clicked, show entire code.

**Comment by vigsterkr** [comment]
yeah but you can show the listing with a simple javascript snippet on the same page in a nice way

**Comment by naruarjun** [comment]
I just want to clarify some specifics. Should the entire code be visible always on the page or should the code section toggle? Where on the page should I display the code and any other specifications you would like to mention?

**Comment by vigsterkr** [comment]
@naruarjun there should be a button/hyperlink for getting the full listing. by default the full listing should not be shown....

**Comment by gf712** [comment]
@naruarjun are you still working on this?

**Comment by karlnapf** [comment]
looks stale to me, and there is not really any added code.
Can be re-opened if needed

**Pull request closed without merging**
