### PR TITLE
Fix vectors in meta langauge in java modular.

### PR DESCRIPTION
**Pull request by karlnapf**
Since SWIG typemaps do assume row vectors from jblas, the default constructor of jblas `DoubleMatrix(size)` results in Shogun thinking that passed vectors have size 1 rather than `size`.

Kudos to @OXPHOS for spotting this in #3282 #3303

### CODE REVIEW

**Comment by karlnapf** [comment]
@OXPHOS after this change, your chaid tree example works locally for me. I'll merge once travis is happy

**Comment by karlnapf** [comment]
@vigsterkr it is kind of annoying that the build is always marked as failing from the AppVeyor ....

**Comment by vigsterkr** [comment]
@karlnapf let's merge `feature/window` :) and then it's all good... although it still has 2 errors... soooo? :)

**Comment by karlnapf** [comment]
Ah I see ...
Lets merge is anyways? I dont know how to fix them as I dont have windows ....
Any ideas?

**Comment by vigsterkr** [comment]
you odnt need windows to fix them :) that's why you have appveyor :)

**Comment by OXPHOS** [comment]
It still fails for me with the same reason (and it failed on travis of this PR):
```
147/168 Test #147: generated_java-multiclass_classifier-cartree ...........................***Failed    0.21 sec
Exception in thread "main" java.lang.RuntimeException: [ERROR] In file /opt/shogun/src/shogun/multiclass/tree/CARTree.cpp line 270: Length of m_nominal vector (currently 1) should be same as number of features in data (presently 2)
```
I have tried to use `IntMatrix` to initiate a vector directly instead of `IntVector`. Also I tried to switch the rows and columns, from `"IntVector": "DoubleMatrix $name = new DoubleMatrix(1, $arguments)` to `"IntVector": "DoubleMatrix $name = new DoubleMatrix($arguments, 1)". But neither of these solved the problem.

**Comment by OXPHOS** [comment]
Also I am currently getting errors when building meta examples at local. So far I haven't found any clue about the cause of the errors...
```
[ 91%] Generating examples from meta-language
Translating binary_classifier/kernel_svm.sg
Generating LALR tables
Syntax error in input: 1.0 on line 14
Syntax error in input: 0.001 on line 15
Syntax error in input: 15 on line 16
Translating binary_classifier/lda.sg
Generating LALR tables
Translating binary_classifier/linear_svm.sg
Generating LALR tables
Syntax error in input: 1.0 on line 14
Syntax error in input: 0.001 on line 15
```

**Comment by karlnapf** [comment]
@OXPHOS ping me in irc about such things, faster :)
Re-build shogun to solve the last error.
The first one works for me locally, can you maybe reproduce this on travis in a PR?

**Pull request merged**
