### PR TITLE
Moved compute_eigenvectors from SGMatrix to eigensolver

### PR DESCRIPTION
**Pull request by srgnuclear**

### CODE REVIEW

**Comment by srgnuclear** [comment]
i need answers to above comment to work ahead.

**Comment by srgnuclear** [comment]
Eigenvectors are being computed in SGMatrix which uses LAPACK methods to do so. While implementing in EigenValues.h in src/shogun/mathematics/linalg/internal/implementation we have to do for eigen3 backend so i found http://eigen.tuxfamily.org/dox/classEigen_1_1EigenSolver.html which illustrates the use of Eigen::EigenSolver to find eigenvalues and eigenvectors.

**Comment by srgnuclear** [comment]
https://gist.github.com/srgnuclear/9f71eb28d68d5f757d3f this is a gist on EigenValues.h in implementation folder. Is it ok?

**Comment by srgnuclear** [comment]
https://gist.github.com/srgnuclear/86d20f2754a9ddfb1d41 this is a gist of eigensolvers.h in modules.

**Comment by lambday** [comment]
- I'm afraid that this is not how `Map` is used in Eigen3. Please read the documentation and see some examples. We have used `Map` in plenty of places inside shogun. Maybe those can help you a bit.
- Did you compile the code _at all_ ? I can see a missing semicolon [here](https://gist.github.com/srgnuclear/9f71eb28d68d5f757d3f#file-eigenvalues-h-L50).
- `MatrixBase` has a `eigenvalues()` method already, so maybe you can use it instead of the `EigenSolver` class.
- eigenvalues of a `double` valued matrix can be `complex`. You should consider that (hint: don't use same `T` for the matrix and the vector containing eigenvalues)
- I'd rather put `eigenvalues` and `eigenvectors` together inside some `eigensolver` struct. We can have overloaded `compute` method for eigenvalues and eigenvectors. Also, I'd keep the filename as `EigenSolvers.h` instead.
- You should ensure that the provided vector has been allocated with enough memory to accommodate all the eigenvalues (sanity check)

I'd suggest that you experiment a bit with Eigen3 locally before pushing shogun code _if_ you want to work on this issue. Its alright to not know these things right away - do some tests, get your hands dirty with Eigen3 first :)

**Comment by srgnuclear** [comment]
Sure i like to work on this issue, as this was the first time there have been mistakes i ll correct and send the updated code.

**Comment by srgnuclear** [comment]
Sure i like to work on this issue, as this was the first time there have been mistakes i ll correct and send the updated code.

**Comment by lambday** [comment]
@srgnuclear any updates man? :)

**Comment by srgnuclear** [comment]
I am really sorry for the delay had my periodical tests which finished on Monday. I have been through the points you asked me to look into i ll implement it and ask for review asap.

**Comment by lambday** [comment]
No worries. Just wanted to make sure that you're still up for this :)

**Comment by karlnapf** [comment]
I hope your tests went well @srgnuclear 
Any news on this one?

**Comment by karlnapf** [comment]
closing since inactive

**Pull request closed without merging**
