### PR TITLE
fixed memory leak in GP

### PR DESCRIPTION
**Pull request by yorkerlin**

### CODE REVIEW

**Comment by yorkerlin** [comment]
@karlnapf 
@vigsterkr

**Comment by yorkerlin** [comment]
I merge this.

**Comment by karlnapf** [comment]
Valgrind checked?

**Comment by yorkerlin** [comment]
Yes. This PR fixed some memory leak in GP.
These bugs disappeared after I merged this PR.
Please see http://buildbot.shogun-toolbox.org/builders/memleak%20-%20valgrind/builds/40/steps/memory%20check/logs/stdio  
```
The following tests FAILED:
	 21 - unit-KMeans (Failed)
	 48 - unit-Serialization (Failed)
	149 - unit-KRRNystrom (Failed)
	232 - unit-Statistics (Failed)
	268 - unit-SerializationHDF5 (Failed)
	297 - libshogun-converter_stochasticproximityembedding (Failed)
	312 - libshogun-library_hdf5 (Failed)
	320 - libshogun-statistics_quadratic_time_mmd (Failed)
	369 - libshogun-statistics_linear_time_mmd (Failed)
	397 - libshogun-statistics_mmd_kernel_selection (Failed)
	402 - generated_cpp-linear_svm (Failed)
	403 - generated_cpp-lda (Failed)
	404 - generated_cpp-kernel_svm (Failed)
	405 - generated_cpp-relaxed_tree (Failed)
	406 - generated_cpp-multiclass_linearmachine (Failed)
	407 - generated_cpp-gaussian_naive_bayes (Failed)
	408 - generated_cpp-shareboost (Failed)
	409 - generated_cpp-knn (Failed)
	410 - generated_cpp-linear_discriminant_analysis (Failed)
	411 - generated_cpp-multiclass_logisticregression (Failed)
	412 - generated_cpp-multiclass_ecoc_random (Failed)
	413 - generated_cpp-quadratic_discriminant_analysis (Failed)
	415 - generated_cpp-gmm (Failed)
	417 - generated_cpp-gaussian_process_regression (Failed)
	418 - generated_cpp-gaussian_process_classifier (Failed)
	419 - generated_cpp-linear_ridge_regression (Failed)
	420 - generated_cpp-support_vector_regression (Failed)
	421 - generated_cpp-multiple_kernel_learning (Failed)
	422 - generated_cpp-kernel_ridge_regression (Failed)
	423 - generated_cpp-feedforward_net_classification (Failed)
```

**Comment by karlnapf** [comment]
Awesome

**Pull request merged**
