### PR TITLE
fixed the variational notebook

### PR DESCRIPTION
**Pull request by yorkerlin**

### CODE REVIEW

**Comment by yorkerlin** [comment]
@karlnapf 
From now on, I will focus on re-factoring the optimization framework.
For GP, the next new features will be structured GP from Andrew's works. I am waiting for his KISS-GP code.

**Comment by vigsterkr** [comment]
@yorkerlin before jumping in alone, could we have like a design session (irc,gdocs, gist) where we can agree on the optimization framework refactoring?

**Comment by yorkerlin** [comment]
yes. Maybe Monday after the GSOC meeting? 
Some ideas:
* using variadic templates
* add parallel coordinate descent solver from https://github.com/uclaopt/TMAC

**Comment by vigsterkr** [comment]
my pain points:
 * kkt solver
 * use the linalg backend so we can use various linalg backends.
 * maybe instead of directly addign TMAC (looks great) work on a more general design?

**Comment by yorkerlin** [comment]
I merge this PR.

**Pull request merged**
