### PR TITLE
Port classifier_averaged_perceptron_modular.py to meta examples.

### PR DESCRIPTION
**Pull request by geektoni**

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks for that! Ill merge the data PR, then you can update this PR here with the new `data` revision

**Comment by geektoni** [comment]
ping @karlnapf ;)

**Comment by karlnapf** [comment]
Ace, thanks!

**Comment by karlnapf** [comment]
Care to write a cookbook page?

**Comment by geektoni** [comment]
That was my initial idea, but currently I am blocked by this #3520. I will probably work on that before writing the cookbook page.

**Comment by karlnapf** [comment]
ok sure

**Pull request merged**
