### PR TITLE
Refactoring for issue #3118

### PR DESCRIPTION
**Pull request by c4goldsw**
Refactored code in reference to #3118 .  Made tests where needed, or used existing tests to see if functions could still work after being refactored.

### CODE REVIEW

**Comment by c4goldsw** [comment]
@karlnapf 4 out of the 6 build failures are being caused by the inability to find the symbol "ZN6shogun11CStatistics8varianceENS_8SGVectorIdEE" when trying to compile builds for the modular interfaces.  How can this be resolved?  The other two are being caused by an example test failure, which should be easy to fix.

**Comment by c4goldsw** [comment]
Closing for fixing.

**Comment by karlnapf** [comment]
Hi
Please never send PRs of this size. 2-3 files max, as few lines of code as possible.
We can re-factor one by one, which is much less error prone

**Comment by c4goldsw** [comment]
@karlnapf I'll keep that in  mind going forward then.  I'll stash the changes I've made and submit PRs individually.  I would still appreciate it if you could look at the build errors, as most of them were caused by the same thing, as mentioned in my second comment - I don't know how to resolve the issue.

**Comment by karlnapf** [comment]
First patch should just add the row/colwise addition -- with unit test. Then the patches with using it should come

**Pull request closed without merging**
