### PR TITLE
LinalgRefactor - enable GPU_WARNINGS switch

### PR DESCRIPTION
**Pull request by OXPHOS**

### CODE REVIEW

**Comment by karlnapf** [comment]
Ok from my side.
@vigsterkr you got thoughts on this?

**Comment by vigsterkr** [comment]
go!

**Comment by vigsterkr** [comment]
@karlnapf @OXPHOS although why compile time? why not runtime parameter? like env var?

**Comment by OXPHOS** [comment]
I do feel like runtime makes more sense now since you mentioned

**Comment by vigsterkr** [comment]
ok here's where it should be implemented, and there you can see how it's done for 2 different env vars:
https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/base/init.cpp#L191-L222

**Comment by OXPHOS** [comment]
@vigsterkr Revised. Not sure whether the var name is too long..

**Comment by vigsterkr** [comment]
ahahah yeah that var SHOGUN_LINALG_LIB_WARNINGS is pretty long :)

**Comment by OXPHOS** [comment]
@vigsterkr Hope it's better now. `SHOGUN_GPU_WARNINGS` doesn't sound accurate to me but it is the most concise one I can think of for now.

**Pull request merged**
