### PR TITLE
Move generated serialization unit tests into separate executable

### PR DESCRIPTION
**Pull request by micmn**
See discussion in #3679

### CODE REVIEW

**Comment by vigsterkr** [comment]
@micmn cool, but you've just copy pasted a bunch of cmake code :) could you maybe define a function/macro for those things and execute it both on shogun-unit-test and shogun-serialization-unit-test... :) thnx!

**Comment by micmn** [comment]
It's ok or it should be defined in `ShogunUtils.cmake`?

**Comment by karlnapf** [comment]
I vote for unitls

**Comment by vigsterkr** [comment]
@micmn i'm invariant regarding this :))) i just wanted to avoid copy-pasting. thnx for the patch!

**Comment by karlnapf** [comment]
Let's merge then

**Pull request merged**
