### PR TITLE
Notebook updated to v3 version and formatted  #3517

### PR DESCRIPTION
**Pull request by amarlearning**
Notebook updated to v3 version and formatted #3517

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks!
Can you post a gist of the notebook with outputs?
Also, can you mention what changed? The diff is not helpful here

**Comment by karlnapf** [comment]
BTW can we please split this patch into two:

1. Just updating the format, no changes at all
2. The changes you did

Thanks!

**Comment by amarlearning** [comment]
> BTW can we please split this patch into two:
> Just updating the format, no changes at all
> The changes you did

@karlnapf ??

**Comment by amarlearning** [comment]
@karlnapf 

1. I have updated the `Author (GitHub ID: githubid)`
2. I also formatted the reference section according to the new [template](https://github.com/shogun-toolbox/shogun/blob/develop/doc/ipython-notebooks/template.ipynb)
3. I also updated the Ipython Notebook to the latest v3.

You can see the preview of changed notebook [here](https://github.com/amarlearning/shogun/blob/amarlearning-NoteBook/doc/ipython-notebooks/classification/HashedDocDotFeatures.ipynb)

**Comment by karlnapf** [comment]
As we cannot see the changes in your diff (all lines are different due to the format change), can you please send a PR where you only update the format (no other changes) first. Then we merge this, and then you can send the changes you made. This way, I can see them in the diff which is important for future bug hunting (knowing in which patch were which changes etc)

**Comment by amarlearning** [comment]
@karlnapf ok I'll do that!

**Comment by karlnapf** [comment]
Can you make this a single commit? This is called "squashing"

**Comment by amarlearning** [comment]
@karlnapf In the Notebook version updations, the lines of code that are added are `461 - 476` and `479-480`
Only these lines are added, rest is same!

**Comment by amarlearning** [comment]
@karlnapf I'll do that also! :smile: :+1:

**Comment by amarlearning** [comment]
@karlnapf unable to squash! Will open a new PR soon!

**Comment by vigsterkr** [comment]
@amarlearning read git-scm.org how to do it.... git squash has nothing to do with github...

**Comment by amarlearning** [comment]
@vigsterkr I did this : `git rebase -i HEAD~3` after that i renamed two commits from `pick` to `squash` and then save and quit the editor!
But it didn't worked!

**Comment by vigsterkr** [comment]
@amarlearning please refer to https://git-scm.com/doc
a very good documentation.

**Pull request closed without merging**
