### PR TITLE
Add meta example for kernel_diag and kernel_exponential

### PR DESCRIPTION
**Pull request by chinmay81098**
Refer #3555 
All tests passed!!

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks for letting us know :D

Could you add some data files as well? The examples readme explains how

**Comment by chinmay81098** [comment]
@karlnapf created PR for data files.

**Comment by karlnapf** [comment]
You can update the data submodule in this PR to the data PR, then the CI will run the integration tests. See readmes.

**Comment by gf712** [comment]
@chinmay81098 you just have to push the `data` submodule where you updated the integration data

**Comment by karlnapf** [comment]
nice thanks. Once the CI is happy we can merge this.

**Comment by chinmay81098** [comment]
Sure! ,sorry for the misunderstanding on my part.

**Comment by karlnapf** [comment]
No worries at all :)

**Pull request merged**
