### PR TITLE
enable MKL in GP

### PR DESCRIPTION
**Pull request by yorkerlin**
@karlnapf

### CODE REVIEW

**Comment by yorkerlin** [comment]
The Python script can be found at https://gist.github.com/yorkerlin/9a64e00543c10d75db793b843ea00623

**Comment by karlnapf** [comment]
The script should be turned into a cookbook for the GPs......
At least a meta example (super easy)
But I can do that

**Comment by karlnapf** [comment]
Can you please update the news file?

**Comment by karlnapf** [comment]
And as said, an api example would help

**Pull request merged**
