### PR TITLE
Add meta example for isomap converter.

### PR DESCRIPTION
**Pull request by Hephaestus12**

### CODE REVIEW

**Comment by karlnapf** [comment]
seems ok, please change the fname though

**Comment by geektoni** [comment]
There seems to be an issue when testing the new meta example on the integration data (unrelated to the merge conflict). @Hephaestus12 maybe you pushed a different file and then the test does not pass on the CI?

**Comment by Hephaestus12** [comment]
This is where the CI is failing
https://dev.azure.com/shogunml/shogun/_build/results?buildId=3960&view=logs&j=be3b03d7-4089-5ab3-9462-9af4d8b1dcdf&t=92f9e07a-f827-5326-7f00-9de226b0894b&l=1470

But when I run this test on my machine it works:
https://pastebin.com/fgVBEfri

Why might that be?
Also, I don't understand why the merge conflict, I have added just one new file.

**Comment by geektoni** [comment]
> This is where the CI is failing
> https://dev.azure.com/shogunml/shogun/_build/results?buildId=3960&view=logs&j=be3b03d7-4089-5ab3-9462-9af4d8b1dcdf&t=92f9e07a-f827-5326-7f00-9de226b0894b&l=1470
> 
> But when I run this test on my machine it works:
> https://pastebin.com/fgVBEfri
> 
> Why might that be?
> Also, I don't understand why the merge conflict, I have added just one new file.

The merge conflict is caused by the fact that I've merged one of your data PR so your local data submodule is out of sync.

Regarding the error, you might have committed the wrong file or the one in this PR is different from your local one hence the error on the CI.

**Comment by Hephaestus12** [comment]
> The merge conflict is caused by the fact that I've merged one of your data PR so your local data submodule is out of sync.

Right, that makes sense. I'll pull, rebase and push again.

> Regarding the error, you might have committed the wrong file or the one in this PR is different from your local one hence the error on the CI.

Hmm fine, I'll check this out.

**Pull request closed without merging**
