### PR TITLE
Cleaning ipython notebooks. removing non-scipy stack dependencies

### PR DESCRIPTION
**Pull request by rahul13ramesh**
Cleaned ipython notebooks, which involved the following changes

* Changed modshogun -> shogun, changed imports to ```import shogun as sg```, instead of ```from shogun import *```
* Changed code to conform to PEP8 python format
* Removed pylab and pillow.Image imports
* Used try-except clause, to smoothly execute imports(cv2, networkx, sklearn) that cannot be removed
* Replace couple of dead-url's ( [Full list here](https://gist.github.com/Red-devilz/67dee8c8afc2502202b16466ff6da225) )

Other file specific changes
* **HashedDocDotFeatures.ipynb** - Try-Except clause around MKLClassification(needs SVM light to execute)
* **MKL.ipynb** - Changed color to plot, to green to distinguis colour
* **xval_modelselection.ipynb** - Added mplot3d
* **gaussian_processes.ipynb** - moved legend location, for better plot visibility
* **Scene_classification.ipynb** - Fixed cv2, error due to change in API in new cv2 verion
* **multilabel_structured_prediction.ipynb** - Fixed error in sklearn, due to change in API

The only notebook that executes with errors is multiclass/tree/DecisionTrees.ipynb, possibly due to #4089. This has been left as is, since it could be a shogun bug

### CODE REVIEW

**Comment by karlnapf** [comment]
This is **great**! Thanks for the patch.
I have one (annoying) re-structuring request: Could you send a PR where you store all those notebooks in your new format without doing any changes first? The diff is totally useless otherwise, and I cannot read through all of the notebooks in source code. Make sure to not loose your changes when doing this :)

**Comment by karlnapf** [comment]
@iglesias now your notebook preview builder would be handy ;)

**Comment by Red-devilz** [comment]
Sure, I'm on it. Just to clarify, you want a separate PR, right? The first commit involves no changes to code(just changing ipython v3 -> v4) Then perhaps a commit changing indentation, formatting, extra spaces and last few commits changing code.

**Comment by vigsterkr** [comment]
@Red-devilz yeah indeed the idea is that we somehow separate automated changes - see v3->v4 - from actual code change, i.e. bug fixes

**Comment by karlnapf** [comment]
Any updates?

**Pull request closed without merging**
