### PR TITLE
Move GPL code to gpl subdirectory

### PR DESCRIPTION
**Pull request by karlnapf**
WIP

Done:
 * classifier

### CODE REVIEW

**Comment by karlnapf** [comment]
#3786

**Comment by vigsterkr** [comment]
there's a problem actually with the cmake file i think; some `___` gets added from somewhere in the build directory path, see:
`build/src/shogun/CMakeFiles/libshogun.dir/__/gpl/shogun/`

**Comment by vigsterkr** [comment]
although this is not related to this PR rather in general of the gpl build

**Comment by karlnapf** [comment]
Fine to merge this despite the formatting errors? I will fix the cmake thing after having moved the files ...

**Pull request merged**
