### PR TITLE
Visually compare multiple classification methods

### PR DESCRIPTION
**Pull request by youssef-emad**
@karlnapf the Notebook for issue #2718

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks for that! Will comment tomorrow. BTW whenever sending a notebook, paste the [link](https://github.com/youssef-emad/shogun_notebooks/blob/master/Classification.ipynb) of the latest version so that it is easy to have a look at it

**Comment by youssef-emad** [comment]
@karlnapf I'll take care next time. Looking forward to your comments :smiley:

**Comment by karlnapf** [comment]
Please run a spell checker, there are a few typos in the notebook, e.g. "This Notebook demonstartes different classification methods in shogun." should be "This notebook demonstrates different classification methods in Shogun."

**Comment by karlnapf** [comment]
pls dont use %pylab inline but be explicit about all imports

**Comment by karlnapf** [comment]
Can you write a few sentences in the intro. Say that you care comparing the decision boundaries and classifier scores on two datasets, where one is linear seperable, and one is not

**Comment by karlnapf** [comment]
All plots should have axis labels and titles. For axis labels you can use latex, e.g. `plt.xlabel(r"$x_1$")` or similar

**Comment by karlnapf** [comment]
```
#train
linear_svm_1.train()
```
minor: the train comment is not necessary if the method is called train ;)

**Comment by karlnapf** [comment]
I think it would be a good idea to restructure things a bit.
 
 * Use more instructive names than `shogun_features_1/2`, e.g. `feats_linear, feats_nonlinear`
 * Have a method that visualises a *single* classifier
 * Avoid `linear_svm_1`, `linear_svm_2`, in a single cell, but just build a single model and call the above method:
  ```
c  = 0.5
epsilon =1e-3
svm = LibLinear(c,feats_linear,labels_linear)
svm.set_liblinear_solver_type(L2R_L2LOSS_SVC) # would be cool to offer a constructor call to avoid this and the next method. Feel free to send another PR.
svm.set_epsilon(epsilon)
svm.train()
plt.subplot(121)
plot_model(svm)
svm.train(feats_nonlinear, labels_nonlinear)
plt.subplot(122)
plot_model(svm)
  ```

**Comment by karlnapf** [comment]
Avoid Python warnings
```
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':
```

**Comment by karlnapf** [comment]
Avoid outputs such as
`Out[11]: True`

**Comment by karlnapf** [comment]
All the kernels and classes mentioned should contain a link to the class docs.
Use it like [CGaussianKernel](shogun.ml/CGaussianKernel )

**Comment by karlnapf** [comment]
Really nice work.

As a final plot, could put all those plots in a big grid like [this](http://scikit-learn.org/stable/_images/plot_classifier_comparison_001.png)?

**Comment by karlnapf** [comment]
Thanks for the patch.

We usually do a couple of iterations over such notebooks before we merge them. It might seem a bit tedious to react to all those comments, but it really increases the quality of our public notebooks -- once uploaded, they usually do not get touched again, so we gotta make them nice in the first place ;)

Looking forward to the update

**Comment by youssef-emad** [comment]
@karlnapf The changes are easy to make and won't take much time. I was out all day and really tired right now so I will make the pull request tomorrow morning ASAP :smile:

**Comment by youssef-emad** [comment]
@karlnapf check [that](https://github.com/youssef-emad/shogun/blob/develop/doc/ipython-notebooks/classification/Classification.ipynb)
Looking forward forward to your comments.
note: I used two instances from each classifier so I can used them at the final plot.

**Comment by karlnapf** [comment]
See datasets [here](https://github.com/shogun-toolbox/shogun-data/tree/master/toy)

**Comment by youssef-emad** [comment]
@karlnapf The nonlinear labels vector is a vector of 80 labels while the non linear features has 100 observations. Should I use the first 80 ?

**Comment by youssef-emad** [comment]
@karlnapf i used the new datasets.

**Comment by youssef-emad** [comment]
@karlnapf i used the new datasets. check it [here](https://github.com/youssef-emad/shogun/blob/develop/doc/ipython-notebooks/classification/Classification.ipynb)
looking forward to your comments.

**Comment by youssef-emad** [comment]
@karlnapf any updates ?

**Comment by karlnapf** [comment]
Minor typos:

"Shogun.The"  -- missing space after period
"This Notebook" -- small n

**Comment by youssef-emad** [comment]
The typos :disappointed: 
ok I'll fix them right now.

**Comment by karlnapf** [comment]
Can you give all your Python functions one-liner comments what they do
```Python
def function(...)
"""
This functions does nothing
"""
```

**Comment by karlnapf** [comment]
"Shogun provide Liblinear which is a library for large- scale"
should be
"Shogun provides Liblinear, which is a library for large-scale"

**Comment by karlnapf** [comment]
Naive Bayes

you changed font size of the links from here

**Comment by karlnapf** [comment]
Great, so this is ready to be merged :)

In order to do so, please remove all cell outputs -- we dont want the pictures to be in the file.
Also please make sure the notebook runs through from scratch without error (I cannot check this here)

**Comment by youssef-emad** [comment]
@karlnapf sorry but I don't understand your comment bout Naive Bayes.

**Comment by karlnapf** [comment]
Sorry about the comment, it was unclear.

Try to make "Support Vector Machine" also a link to the CSVM class docs, just like Naive bayes
Same for "SVM - Kernels"  -- mention the CKernelMachine interface

**Comment by youssef-emad** [comment]
@karlnapf I made the needed changes.check [here](https://github.com/youssef-emad/shogun/blob/develop/doc/ipython-notebooks/classification/Classification.ipynb)
For removing cell outputs I just commented `%matplotlib inline` . Is that ok ?

**Comment by karlnapf** [comment]
Can you also link the CKernelMachine base class when you first talk kernel SVMs?

**Comment by karlnapf** [comment]
and for the output, leave the matplotlib inside (we need it), but just select cell->remove all outputs in the menu of the ipython notebook

**Comment by youssef-emad** [comment]
@karlnapf [done](https://github.com/youssef-emad/shogun/blob/develop/doc/ipython-notebooks/classification/Classification.ipynb).

**Comment by karlnapf** [comment]
Nice one! I will merge it! This our first larger GSoC student patch :)

**Comment by erip** [comment]
I might recommend using [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) in Python instead of traditional `#` comments. Very nice looking notebook overall! :+1:

**Comment by karlnapf** [comment]
I agree on the docstrings -- in fact I put them in my above comment. Can you update, @youssef-emad ?

**Comment by youssef-emad** [comment]
@karlnapf @erip  Thanks, I am glad it's finally merged :smiley: 
For the docstrings, should I make a new pull request since it's merged or just a new commit ?

**Comment by karlnapf** [comment]
yes, a small one :)

**Pull request merged**
