### PR TITLE
modified () operator for sparse matrix to be consistent with dense matrix

### PR DESCRIPTION
**Pull request by yingryic**
not sure anywhere else still using the sparse matrix () operator, but get all the unit test passed. tell me what you think. @iglesias @karlnapf #2769

### CODE REVIEW

**Comment by iglesias** [comment]
I am really surprised to see that nothing breaks after this change! Does this mean that `SGSparseMatrix` is not really used anywhere? I would expect that all around where `SGSparseMatrix::operator()` is used, the features and vector indices should be swapped. Am I missing something?

**Comment by karlnapf** [comment]
Careful!

This is the final patch, see list here: http://permalink.gmane.org/gmane.comp.ai.machine-learning.shogun/5463
We cannot merge this without being absolutely certain that it doesnt break things.

You  basically have to search for all places where SGVSparseMatrix is imported and then check for the () operatior being invoked. A bit messy.

**Comment by karlnapf** [comment]
However, after thats done, we can merge. Thanks a lot for your help

**Comment by iglesias** [comment]
I don't think there is any risk as the operator() is used nowhere but the unit test.

**Comment by iglesias** [comment]
In fact, I really wonder whether we need it if it is not used.

**Comment by karlnapf** [comment]
It kind of is a dangerous thing for sparse structures as one should always iterate through the list of non-zero elements

**Comment by yingryic** [comment]
@karlnapf I checked before, actually the () operator is not used anywhere except for one unit test (ProbingSample test), where it constructed a symmetric matrix, thus the order actually doesn't matter.

**Comment by karlnapf** [comment]
Sorry for the late reply.
I agree if it is not used then the order doesnt matter.
We should probably unify the interface with other langauges as @iglesias suggested.

**Pull request closed without merging**
