### PR TITLE
attempt to fix csharp build via hiding implementation from SWIG

### PR DESCRIPTION
**Pull request by karlnapf**

### CODE REVIEW

**Comment by vigsterkr** [comment]
no bueno! we should fix the typemaps in the swig definition of csharp

**Comment by karlnapf** [comment]
sure, I agree, but this patch [here](https://github.com/shogun-toolbox/shogun/commit/7f15f5e1ca1fef6507e2a1ce800b9a21366d0240) [broke](http://buildbot.shogun-toolbox.org/builders/deb3%20-%20modular_interfaces/builds/2643/steps/csharp%20modular/logs/stdio) csharp modular.

I just try to get the build working again for the release. 
Happy to fix that properly after.

What is your suggestion with the typemap?

**Comment by vigsterkr** [comment]
why after and not before? :)

**Comment by karlnapf** [comment]
I don't know how to do it and nobody else does it.
Or can you prove me wrong? :)

**Comment by vigsterkr** [comment]
well let's at least give it a go before just signing off of not doing it :)

**Comment by karlnapf** [comment]
ok cool. It's one of the last things before we can release I think

**Comment by karlnapf** [comment]
Also, the patch did not work. closing.

**Comment by karlnapf** [comment]
@sonney2k told me this comes from having duplicate method signatures, btw

**Pull request closed without merging**
