### PR TITLE
add SWIG interface for tags

### PR DESCRIPTION
**Pull request by sanuj**
A few questions:
- How to test this:question: Shall I add meta-language code for testing:question:
- Where to include MockObject in SWIG:question: This will be required for testing.
- Commented out `SG_INSTA` are abstract templates in shogun. @lisitsyn wanted to discuss something about these with @karlnapf or @vigsterkr.

`SG_INSTA` stands for `shogun instantiate`. Can change the name if someone proposes a better one. :smile: 

This code works in Python. [Here](https://gist.github.com/sanuj/e24d003b5af990fee1b772129ace75fa) is some old working example but it won't work with latest changes like registering arbitrary parameters is not allowed now. Will update this example as soon as I know where to put MockObject in SWIG.

### CODE REVIEW

**Comment by sanuj** [comment]
Come on ruby! :gem:

**Comment by karlnapf** [comment]
You can add meta language examples for testing, yes.
If you find that something is incomplete, let me know.
Pls do this in the way I described in #3328 i.e. create a file that is a test and an api illustration for tags at the same time

**Comment by karlnapf** [comment]
No idea about the mock object .... @lisitsyn  ?

**Comment by karlnapf** [comment]
The classes in there are *way* to specific. I dont understand at all why this is done? Can you explain a bit?

**Comment by sanuj** [comment]
@karlnapf These are abstract classes in shogun i.e. they have a pure virtual function. Now the plan has changed. @lisitsyn and I decided to create a new jinja file which will have SWIG interface for set/get/has/Tag and this file will be included in `SGBase.i`. The jinja file will read the names (X) of classes from `shogun-base.txt` and generate code for setX() / getX() / hasX() / TagX in SWIG. Initially we will have 3-4 classes in `shogun-base.txt` and we can keep adding on classes later. `shogun-base.txt` will have list of classes that we want to keep in base shogun.

**Comment by sanuj** [comment]
:eyes: See `add swig for tags using Jinja` #3357.

**Pull request closed without merging**
