### PR TITLE
Fix #3605, Port KernelMachine to OpenMP

### LINKED ISSUE #3605: port parallel code using pthread
There are several parts of the code that uses `pthread` for implementing parallel execution of the algorithms. These should be ported to use either `OpenMP` or C++11 `std::thread` (preferably openmp).

some examples:
 * https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/lib/external/shogun_libsvm.cpp#L270
 * https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/distance/Distance.cpp#L368
 * https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/features/DotFeatures.cpp#L105
 * https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/features/hashed/HashedWDFeaturesTransposed.cpp#L242
 * https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/kernel/CombinedKernel.cpp#L465

for finding the full list use: `git grep HAVE_PTHREAD`

### PR DESCRIPTION
**Pull request by iRmantou**

### CODE REVIEW

**Comment by karlnapf** [comment]
A unit test for single a multi threads of a kernel machine would help

**Comment by iRmantou** [comment]
@karlnapf  I see this PR has passed Travis. Travis CI can't check this , isn't it ? use `./bin/shogun-unit-test`?

**Comment by karlnapf** [comment]
Yeah travis only checks single threaded.
Can you at least memcheck this locally using multiple threads?
If that is ok, we can merge

**Comment by iRmantou** [comment]
@karlnapf ok, just give me some time!

**Comment by iRmantou** [comment]
@karlnapf  there is no unit test for `KernelMachine` in `tests/unit/machine`, isn't it? So I need to create it by myself ?

**Comment by iRmantou** [comment]
Can I use `LibSVR_unittest` which inherited from `KernelMachine`  to test `KernelMachine` ?

**Comment by karlnapf** [comment]
Yes.
Just run it locally with single thread and multiple ones and make sure your patch didn't change the output/result

**Comment by iRmantou** [comment]
result

@karlnapf  Is this right?

**Comment by karlnapf** [comment]
Almost, run this with a memory checker that checks thread safety

http://valgrind.org/docs/manual/hg-manual.html

**Comment by iRmantou** [comment]
@karlnapf  I cleaned the whole `build` directory and recompiled it with my code, so I am sure the unit test use the changed code, then I used `valgrind` , and there is no error message. The results are as follows
varf
Is there anything I might have missed or need to note?

**Comment by karlnapf** [comment]
What I meant is:
Check the unit test code. Does it run things single AND multithreaded.
Also, tell valgrind to use the `helgrind` tool, see above readme

**Comment by iRmantou** [comment]
I have set `export OMP_NUM_THREADS` before I run the unit test.
What I should check or set in the unit test code like : `LibSVR_unittest.cc` to make sure it run things with  multithreaded and single?

**Comment by karlnapf** [comment]
It doesnt really matter how you do it, the point is that you need to be aware what you are checking there. And that needs things to be explicitly executed single and multithreaded

**Comment by karlnapf** [comment]
Any updates here?

**Pull request closed without merging**
