### PR TITLE
Reintegrate parallel crossvalidation

### PR DESCRIPTION
**Pull request by lkuchenb**
Would be great to see this back in develop

### CODE REVIEW

**Comment by vigsterkr** [comment]
@lkuchenb cool! let's see what CI says about this :)

**Comment by karlnapf** [comment]
so travis didnt complain more than the current broken things
@vigsterkr iirc the bugs in the parallel xvalidation with clone were caused by parallel issues that were fixed?

**Comment by vigsterkr** [comment]
@karlnapf i think it was completely other stuff :) only thing we need to test that i vividly remember that for some in one of the ipython notebooks the CV stuff was failing with this .... so somebody should try to run the notebook using this patch (imo there's a CV notebook, or?)

**Comment by vigsterkr** [comment]
@lkuchenb i'll try to finish up the input parser story in cpp11 branch so we can merge and then we can rebase this one to be sure about the MSVC et.al.

**Comment by karlnapf** [comment]
There is one
@lkuchenb wanna have a go at that?

**Comment by vigsterkr** [comment]
wooohooo, getting a parallel CV, how awesome is this in 2017! 💃

**Comment by karlnapf** [comment]
Next step -- don't clone the fucking data. This is madness in 2017 !!!

**Pull request merged**
