### PR TITLE
Fix issue 2766. Changed all 'initialize' methods names

### PR DESCRIPTION
**Pull request by erip**
Refactor methods with name `initialize` to a more meaningful name as to not interfere with Ruby naming.

### CODE REVIEW

**Comment by erip** [comment]
This is so annoying... Travis can't handle the build, so it fails.

**Comment by lisitsyn** [comment]
@erip hey, what's that? :)

**Comment by erip** [comment]
@lisitsyn When Travis builds, some of the tests will pass. When I rebuild (no changes in code), other tests will pass.

**Comment by yorkerlin** [comment]
@erip 
Please try not to do the `open and close` operations.
Travis will fail due to the memory issue.

You can use the following trick:

For example,
* In the first commit, all tests are passed except test 1 and test 2  are failed.
* then do the `git force update` trick without changing the code
* In the second commit, if test 1 and test 2 are passed, you may consider `all` tests  are passed even other tests are failed.

the `git force update` trick is:
```
git reset --soft "HEAD^"
git commit -m "you comments" (the `hash id` will be changed)
git push origin +your_branch (force to update your branch even without no change)
```

**Comment by yorkerlin** [comment]
BTW, @lisitsyn 
It seems currently `test 3` always fail due to the memory issue.

**Comment by erip** [comment]
Ah, sorry. I'm new to OSS, so I didn't know this. My apologies. `test 12` seems to fail always, and I've created an issue in rudix to address it. In this latest build, all tests passed apart from `test 12`.

**Comment by yorkerlin** [comment]
ref
https://github.com/shogun-toolbox/shogun/issues/2766

**Comment by erip** [comment]
Merge?

**Comment by besser82** [comment]
No objections…  Merging…

**Pull request merged**
