### PR TITLE
Meta-Language: Fix C# enum translation rule and uncaught bugs in tran…

### PR DESCRIPTION
**Pull request by sorig**
…slate.py

### CODE REVIEW

**Comment by sorig** [comment]
Fixes problem with enum translations described in #3112 @sanuj @karlnapf

**Comment by sorig** [comment]
I had some trouble compiling on my machine (cmake can't find ctags although it is installed on my machine). 

It should work, but let's see what travis says.

**Comment by karlnapf** [comment]
Thanks a lot for this

**Comment by karlnapf** [comment]
@lisitsyn ctags

**Pull request merged**
