### PR TITLE
Add ICA meta examples and cookbook page for fastICA

### PR DESCRIPTION
**Pull request by karlnapf**

### CODE REVIEW

**Comment by karlnapf** [comment]
#3881

**Comment by karlnapf** [comment]
@vigsterkr can you restart the appveyor build?

**Comment by vigsterkr** [comment]
@karlnapf style problem: https://travis-ci.org/shogun-toolbox/shogun/jobs/248793435#L809
and something with the integration data `integration_meta_cpp-converter-ica_u_wedge_sep`

**Comment by karlnapf** [comment]
Merging as AppVeyor was fine earlier (and just removed things)

**Comment by karlnapf** [comment]
@vigsterkr Are the meta languages cpp included in the coverage?

**Pull request merged**
