### PR TITLE
Add Range for beautiful for-loops

### PR DESCRIPTION
**Pull request by lisitsyn**
This PR adds a class and two helper functions to support python-like loops:

```cpp
for (auto i : range(elements.size())) { ... }
```

### CODE REVIEW

**Comment by besser82** [comment]
LGTM =)  Travis fails, because of the random issue with finding some unittest-executables…  Not related to the changes.

@lisitsyn Rdy 2 merge?

**Comment by lisitsyn** [comment]
@besser82 actually one issue is to be fixed

**Comment by besser82** [comment]
@lisitsyn Allrighty!  Let's wait for Travis.  If all goes fine, I'll merge?

**Comment by lisitsyn** [comment]
@besser82 yeah I think so

**Comment by besser82** [comment]
@lisitsyn A'ight!  =)

**Comment by besser82** [comment]
@lisitsyn Travis was fine with the gcc / clang part…  other stuff isn't related…  Merging.

**Pull request merged**
