### PR TITLE
Newnotebook

### PR DESCRIPTION
**Pull request by yorkerlin**

### CODE REVIEW

**Comment by yorkerlin** [comment]
@karlnapf 
the notebook may take a long time to run, which causes the timeout issue.
see 
http://buildbot.shogun-toolbox.org/builders/nightly_default/builds/1018/steps/notebooks/logs/stdio

**Comment by karlnapf** [comment]
Let's try it. But currently cannot merge, there is a conflict

**Comment by yorkerlin** [comment]
@karlnapf 
let's see whether the timeout error is fixed.
I merge it now since errors reported by travis are not related to this PR.

**Comment by karlnapf** [comment]
For future: pls try to squash commits with redundant titles. Keeping the git log clean

**Pull request merged**
