### PR TITLE
Drop old preprocessor and converter api

### PR DESCRIPTION
**Pull request by vinx13**

### CODE REVIEW

**Comment by lisitsyn** [comment]
This looks good, @vigsterkr ?

**Comment by lisitsyn** [comment]
This looks good, @vigsterkr ?

**Comment by vinx13** [comment]
python build failed because log exceed maximum length
appveyor failed because of timeout

**Comment by karlnapf** [comment]
restarting ...

**Comment by karlnapf** [comment]
I'll leave it to @vigsterkr to merge this though

**Comment by vigsterkr** [comment]
i had to fix some errors in the feature branch... it should be good now, as soon as things gets green in CIs i'm merging this and then i merge the whole feature branch into develop

**Pull request merged**
