### PR TITLE
added documentation for the FactorAnalysis class

### PR DESCRIPTION
**Pull request by curiousguy13**
in reference to: #2673 
added documentation for the FactorAnalysis doxygen class mainly from here: http://tapkee.lisitsyn.me/
is there any other relevent info about Factor Analysis that i can add here?

### CODE REVIEW

**Comment by iglesias** [comment]
Thanks for polishing the documentation. I will merge this but next time, please use only one commit for a change as small as this one. You can squash more than one commit into one after having done them.

**Comment by curiousguy13** [comment]
Alright , thanks for the tip. I'll remember it for next time. :)

**Comment by karlnapf** [comment]
If you want infos on FA, check david barber's book "Bayesian reasoning and machine learning", which is available online.

I would love to see the math for the generative model of FA in the docs. Also a good thing to learn about

**Comment by curiousguy13** [comment]
I'll definitely check it out :)

**Pull request merged**
