### PR TITLE
added support for configuring neural networks using JSON files

### PR DESCRIPTION
**Pull request by khalednasr**

### CODE REVIEW

**Comment by lisitsyn** [comment]
@khalednasr can you please rebase it? I'd like to merge this as well

**Comment by iglesias** [comment]
I have fixed the conflict (trivial thing) locally and submitted a new PR #2680.

**Comment by iglesias** [comment]
Now merged, @lisitsyn.

**Comment by lisitsyn** [comment]
Cool, thanks @iglesias !

**Pull request closed without merging**
