### PR TITLE
Remove migration and disable integration testing

### PR DESCRIPTION
**Pull request by karlnapf**
To see what travis says to this. Not yet to merge

### CODE REVIEW

**Comment by karlnapf** [comment]
@lisitsyn this looks good doesnt it?
Shall we merge before release?

**Comment by karlnapf** [comment]
@iglesias @vigsterk Any objections?

**Comment by vigsterkr** [comment]
kill it! :)

**Comment by karlnapf** [comment]
Here we go

**Comment by iglesias** [comment]
Getting leaner :-)

For reference see #1253.

**Pull request merged**
