### PR TITLE
edited some typos in the notebook

### PR DESCRIPTION
**Pull request by nouranali**

### CODE REVIEW

**Comment by nouranali** [comment]
@gf712

**Comment by nouranali** [comment]
@karlnapf

**Comment by karlnapf** [comment]
@nouranali no need to ping us. We receive an email upon PR

**Review by karlnapf — APPROVED** [review]
thanks! These are useful.
Ill leave merging to @gf712 as he was doing a PR touching all notebooks

**Comment by gf712** [comment]
Thanks!

**Pull request merged**
