### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by Saurabh7**

### CODE REVIEW

**Comment by Saurabh7** [comment]
Pls do NOT merge, need to add more fixes.

**Comment by karlnapf** [comment]
Is this a fix for the recent broken test?

If not, changing names of parameters breaks integration tests, so they also need to be updated

**Comment by Saurabh7** [comment]
I had changed the names of parameters already, so thats what broke the test. Sry about that. This was just a typo. i ill check if everything is fine and get back. Thanks!

**Comment by karlnapf** [comment]
cool! let me know how it goes

**Pull request closed without merging**
