### PR TITLE
Issue #2730: Update Methods list [FIX]

### PR DESCRIPTION
**Pull request by adit-39**
Have updated the *completed*  **features**, **preprocesssors**, **kernels**, **distance measures** and **methods** based on the implementations found under respective directories in *src/shogun* instead of only the examples folder. Hope that is alright as it seemed to contain a more complete list than that in examples.

### CODE REVIEW

**Comment by iglesias** [comment]
Nice job, @adit-39. Good decision to check the directories instead of the examples. Since you are on it, it would be also nice if you detect the classes that are missing unit tests and/or api examples. Those should be implemented so we can, for instance, start creating entrance issues for them.

**Comment by adit-39** [comment]
@iglesias sure, will get down to it! :)

**Comment by adit-39** [comment]
@iglesias do you want separate lists of those without unit tests, those without examples and those without both?

**Comment by iglesias** [comment]
A GitHub issue sounds reasonable to me. In the issue, you can have two separate lists: one with the missing unit tests, another one with the missing examples.

As they start gradually getting done, we can update those lists. Also, the PRs addressing missing unit tests and/or examples should reference the issue.

**Pull request merged**
