### PR TITLE
Fixed memory leak in LDA unit test

### PR DESCRIPTION
**Pull request by c4goldsw**

### CODE REVIEW

**Comment by karlnapf** [comment]
So I guess the leak was due to a forgotten SG_UNREF?

Is the unit test binary checked with valgrind? Or at least your test now?

**Comment by c4goldsw** [comment]
I ran ```valgrind ctest -R LDA -VV``` and no leaks were reported.

**Comment by karlnapf** [comment]
Nice one!

**Comment by c4goldsw** [comment]
@karlnapf So, buildbot says there's a leak still [according to build bot](http://buildbot.shogun-toolbox.org/builders/memleak%20-%20valgrind/builds/4/steps/memory%20check/logs/stdio).  ```valgrind ctest -R LDA``` [is not reporting any leaks](https://gist.github.com/c4goldsw/ad3f6dcb1cc05a0ebbe879f7addc3f3b).  Do you know what the issue could be?  Should the command above be sufficient for checking for leaks?

**Comment by karlnapf** [comment]
Thanks for the nice report. I actually dont know what is going on there. maybe @vigsterkr knows?

**Pull request merged**
