### PR TITLE
Fix matrix string

### PR DESCRIPTION
**Pull request by gf712**
fixes SGMatrix string

### CODE REVIEW

**Comment by vigsterkr** [comment]
NOOOOOOOOOOOO
```
@gf712
Merge branch 'develop' into develop 
```
and

```gf712
Merge branch 'develop' of https://github.com/gf712/shogun into develop
```

ppffff

**Comment by karlnapf** [comment]
que?

**Comment by vigsterkr** [comment]
@karlnapf just merged junk into develop (see those 8 commits...)

**Comment by karlnapf** [comment]
no i didnt, check the log

**Pull request merged**
