### PR TITLE
Shorten time and diagnose failing python modular examples.

### PR DESCRIPTION
**Pull request by sanuj**
For #3005.
I haven't touched those that use shogun-data. Final output of `make test` after changes is [here](https://gist.github.com/sanuj/36dbf0ff8af9de9c8468).

### CODE REVIEW

**Comment by sanuj** [comment]
5 tests which were not passing before are now passing.
**Before:**
```
The following tests FAILED:
	330 - python_modular-evaluation_cross_validation_multiclass_storage (Failed)
	338 - python_modular-structure_hierarchical_multilabel_classification (Failed)
	346 - python_modular-preprocessor_fisherlda_modular (Failed)
	366 - python_modular-modelselection_grid_search_kernel (Failed)
	403 - python_modular-modelselection_grid_search_krr_modular (Failed)
	458 - python_modular-neuralnets_simple_modular (Failed)
	470 - python_modular-modelselection_parameter_tree_modular (Failed)
	499 - python_modular-serialization_complex_example (Failed)
	501 - python_modular-features_string_char_compressed_modular (Failed)
```
**After:**
```
The following tests FAILED:
	330 - python_modular-evaluation_cross_validation_multiclass_storage (Failed)
	338 - python_modular-structure_hierarchical_multilabel_classification (Failed)
	499 - python_modular-serialization_complex_example (Failed)
	501 - python_modular-features_string_char_compressed_modular (Failed)
```

**Comment by sanuj** [comment]
Interesting. All my changes in the second commit fail on travis but pass on my laptop. I have shogun 4.0.0 installed on my laptop so I think that's making this happen. I'll revert back the second commit.

**Comment by karlnapf** [comment]
traivs timed out. restarted.
Otherwise I am fine.
Good to start with those that dont use shogun-data. Though this is disabled anyways and will be replaced soon

**Comment by karlnapf** [comment]
Thanks for that

**Pull request merged**
