### PR TITLE
Add Gaussian Naive Bayes cookbook page

### PR DESCRIPTION
**Pull request by tbskm**
Add a cookbook entry for Gaussian Naive Bayes and remove all undocumented Gaussian Naive Bayes examples.

### CODE REVIEW

**Comment by tbskm** [comment]
Let me check out that failed build, not sure why that's happening.

**Comment by tbskm** [comment]
I'm going to reopen this to let Travis run so I can see if everything else works correctly. It looks like the Sphinx link validator is looking for `gaussiannaivebayes.py`, but the actual file is `gaussian_naive_bayes.py`. Could somebody help me figure out what's going on here? I don't think Sphinx would ignore underscores as it validates, but I'm not sure where I messed up.

**Comment by karlnapf** [comment]
Please squash all commits into a single one for cookbook PRs

**Comment by karlnapf** [comment]
The PR should also contain an integration test file for the cookbook example. See the readme how to generate it. You will have to send a PR against the data repository and then include the new data version in this PR

**Comment by karlnapf** [comment]
no idea why the error happens, but it does locally for me too. fixing ....

**Comment by karlnapf** [comment]
You referenced the meta example snippets with a wrong filename

**Comment by karlnapf** [comment]
`.. sgexample:: gaussiannaivebayes.sg:create_features`
should be
`.. sgexample:: gaussian_naive_
bayes.sg:create_features`

**Comment by tbskm** [comment]
Aww man, can't believe I didn't catch that. Good eye.

So by "update the data version", do you mean I need to `make test` again once I fix the meta doc, then use the .dat file generated by that?

**Comment by tbskm** [comment]
Closing this to make another PR with the above fixes.

**Pull request closed without merging**
