### PR TITLE
Revert "remove migration methods from all classes and blacklist depending libshogun examples"

### PR DESCRIPTION
**Pull request by besser82**
SerializationASCII heavily depends on migration-framework, so we cannot drop that easy, unfortunately.

This reverts commit 5af68edff0f7ea7100c142d280307a0e7acaf350.

### CODE REVIEW

**Comment by karlnapf** [comment]
I don't think that ASCII serialisation heavily depends on migration framework.
I think there is another reason why things broke. Will have a look and then send the patch again.

**Comment by karlnapf** [comment]
Before you merge this, give me a moment to take a look at the cause

**Comment by karlnapf** [comment]
(in the plane back tomorrow)

**Comment by karlnapf** [comment]
Should be fixed in #2955

**Comment by besser82** [comment]
Going to merge #2955 after Travis is ready…

**Pull request closed without merging**
