### PR TITLE
Added HAVE_EIGEN3 setting

### PR DESCRIPTION
**Pull request by OXPHOS**
- ref issue#3083
- Temporal fix in CMakeList.txt and config.h.in to include Eigen3 library

### CODE REVIEW

**Comment by vigsterkr** [comment]
@OXPHOS thnx for the patch but lets rather fix the unit tests... we really would like to have eigen as a hard dependency.

**Comment by OXPHOS** [comment]
Sure I was just having trouble testing my code. I would like to know how to enable Eigen3 in unit tests if possible. Thanks!

**Comment by vigsterkr** [comment]
ok so you were having problem when you included eigen headers? could you point me to an error, i.e. copy paste to pastebin or something?

**Comment by karlnapf** [comment]
Sorry I just only saw this so my other comments might be outdated

**Pull request closed without merging**
