### PR TITLE
Remove cosine distance and euclidean distance python_modular example

### PR DESCRIPTION
**Pull request by IOcodegeass**
Remove `distance_cosine_modular.py` and `distance_euclidean_modular.py` from python_modular example.

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks!!

**Comment by IOcodegeass** [comment]
@karlnapf build failed :(

I don't know why. I am able to run `make all `in my package while build failed because of compile error.

**Comment by karlnapf** [comment]
No idea what you mean....?

**Comment by IOcodegeass** [comment]
**buildbot failure in shogun-toolbox on precise - libshogun**

**Comment by karlnapf** [comment]
Check the history the error is not caused by you: http://buildbot.shogun-toolbox.org/builders/precise%20-%20libshogun

**Pull request merged**
