### PR TITLE
Fix possible IndexError and/or TypeError in undocumented/python_modular

### PR DESCRIPTION
**Pull request by besser82**

### CODE REVIEW

**Comment by besser82** [comment]
Yes!  =)  Just packaging v6.0.0 for Fedora  ;)

**Comment by besser82** [comment]
Please check https://github.com/shogun-toolbox/shogun/pull/3801 first…  ;)

**Comment by lisitsyn** [comment]
Does it really fail on some platform? I am curious what makes it fail.

**Comment by besser82** [comment]
For me it those four tests fails on any platform, when building on RHEL or Fedora…  :(

**Comment by lisitsyn** [comment]
Do you happen to know what is the type *before* the cast? The whole world looks fragile to me if range produces not ints but something.

**Comment by besser82** [comment]
They are float() before.

**Comment by lisitsyn** [comment]
Oh I still don't get where floats come from but lets merge it 👍

**Comment by besser82** [comment]
Okie, will do so  =)

**Pull request merged**
