### PR TITLE
Active Appearance model notebook added

### PR DESCRIPTION
**Pull request by kislayabhi**
nbviewer link: http://nbviewer.ipython.org/gist/kislayabhi/0cc4f6e6b625873c15de

### CODE REVIEW

**Comment by karlnapf** [comment]
We need to close this soon due to inactivity.
It would be a pitty to lose the cool notebook though ...

**Comment by kislayabhi** [comment]
Hey! Can you guys give me some ideas here on using Shogun. I can resume. (I am still young)

**Comment by iglesias** [comment]
A first easy step would be to address the comments above, @kislayabhi :-)

Afterwards, what about using a publicly available face recognition data set and test some classifiers using your APM?

**Comment by karlnapf** [comment]
Agreed with @iglesias 

Let's aim to merge this soon. Need to clean up our open PRs

**Comment by kislayabhi** [comment]
@karlnapf , I think closing this PR for now would be okay. Will take care of the above comments and @iglesias ideas in a new PR later.

**Pull request closed without merging**
