### PR TITLE
First shot to fix the reported median bug.

### PR DESCRIPTION
**Pull request by iglesias**
Hi!

It is still work in progress. Just in case, apologies for opening the pull request already.

### CODE REVIEW

**Comment by lisitsyn** [comment]
LGTM!

**Comment by iglesias** [comment]
It doesn't seem to be reproducible. At least to me 🤷‍♂️

https://godbolt.org/z/P4b1sbcsW

**Comment by danlark1** [comment]
You should put the define before includes or in the command line, see

https://godbolt.org/z/Tx8rGrqoa

**Comment by danlark1** [comment]
Or, for example, without any randomization

https://godbolt.org/z/vn5e7eW7M

**Comment by iglesias** [comment]
Oh! Thanks a lot for taking a look and getting back!

**Pull request merged**
