### PR TITLE
LinalgRefactor - matrix block sum

### PR DESCRIPTION
**Pull request by OXPHOS**
incomplete.

### CODE REVIEW

**Comment by karlnapf** [comment]
rebase

**Comment by vigsterkr** [comment]
@OXPHOS please rebase :)

**Comment by OXPHOS** [comment]
@vigsterkr ready

**Comment by vigsterkr** [comment]
@OXPHOS this is complete now, right? if so i'll merge

**Comment by OXPHOS** [comment]
@vigsterkr yes please go ahead

**Pull request merged**
