### PR TITLE
LinalgRefactor - Remove old linalg::mean

### PR DESCRIPTION
**Pull request by OXPHOS**
This will make #3399 easier

### CODE REVIEW

**Comment by lambday** [comment]
Thanks @OXPHOS. Can merge as soon as travis is done :)

**Comment by OXPHOS** [comment]
@lambday thanks! but i'm already getting weird failures..errors downloading googlemock? Is this some kind of temporary connection issue?

**Comment by lambday** [comment]
Let me restart the job.

**Comment by OXPHOS** [comment]
@lambday @karlnapf still failed to fetch GoogleMock...Any idea why this is happening? It worked well for me at local

**Comment by karlnapf** [comment]
I think if you rebase it should work

**Comment by OXPHOS** [comment]
I tried `git rebase upstream/feature/linalg_refactor`
And got `Current branch linalg_mean_remove is up to date.`

**Comment by vigsterkr** [comment]
@OXPHOS did you do a `git fetch` before that?

**Comment by yorkerlin** [comment]
The issue may be related to the `cmake` configuration. 
Note:
In the `develop` branch, `GoogleMock 1.8` is used.
In this PR,  `GoogleMock 1.7` is used. However, this old version is removed from the URL.
Make sure that you use/update the updated `cmake` configuration.

**Comment by vigsterkr** [comment]
mmm we should not have this thing .... we should just rebase the base feature branch to latest develop as that one already has the right mock thingy

**Comment by OXPHOS** [comment]
@yorkerlin Thanks that is the problem! Never thought about that. @vigsterkr I temporarily added the change of `cmake` files to a separate push

**Comment by karlnapf** [comment]
I can rebase the feature branch..... shall I?

**Comment by OXPHOS** [comment]
@karlnapf This should be ready

**Comment by karlnapf** [comment]
rebase

**Comment by OXPHOS** [comment]
@karlnapf reported failure:
```
[ 94%] Building CXX object tests/unit/CMakeFiles/shogun-unit-test.dir/SerializationHDF5_unittest.cc.o
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
I assume this is not relevant..?

**Comment by karlnapf** [comment]
Nope not relevant ... restarting

**Pull request merged**
