### PR TITLE
Add svmlin & svmsgd meta example

### PR DESCRIPTION
**Pull request by vinx13**
Two files are missing from previous pr #4361, data shogun-toolbox/shogun-data#168
See also #4400

### CODE REVIEW

**Comment by karlnapf** [comment]
What’s the errors?

**Comment by karlnapf** [comment]
uff this seems like a python version problem. Can you reproduce this error locally? I bet it is some upgrade to Python 3

**Comment by vinx13** [comment]
some error on windows about variant since 7c7693f81974191b377245ea4f, i guess that's some compiler version issue

**Comment by karlnapf** [comment]
the windows variant error for sure is compiler version
But the Python error, what about that? We should get at least travis green

**Comment by vinx13** [comment]
@karlnapf travis gets green now

**Comment by karlnapf** [comment]
Great, thanks for the ping and let's merge

**Comment by karlnapf** [comment]
@vinx13 would you min checking the variant compiler error on windows? At least googling the source a bit?

**Comment by vinx13** [comment]
the variant error on windows seems a MSVC issue, see https://github.com/mpark/variant/pull/49
I will update version of variant

**Pull request merged**
