### PR TITLE
update em_1d_gmm.py

### PR DESCRIPTION
**Pull request by mohitmajithia**
made ur changes #4990

### CODE REVIEW

**Comment by gf712** [comment]
Could you just put all this in the same PR please?

**Comment by mohitmajithia** [comment]
hey i am beginner can u tell how? thanks!

**Comment by gf712** [comment]
> hey i am beginner can u tell how? thanks!

You started #5023 which is the same refactor, so in future could you just put all of this type of refactor in a single PR please?

**Comment by mohitmajithia** [comment]
how to put in single pr?

**Pull request closed without merging**
