### PR TITLE
Replace pointers with SGVector

### LINKED ISSUE #3507: clean up KNN
Currently, there are multiple solvers used in KNN.
All of this is done in a flat structure in a single implementation file.
This task is to build a version that respects the object oriented paradigm, i.e. each implementation is done in a different (sub)class. This will increase code readability, cleanliness, and ease of debugging.

This is mostly copy paste plus some minimal standard design decisions

### PR DESCRIPTION
**Pull request by souravsingh**
Update pointers to SGVector.

Fixes #3507

### CODE REVIEW

**Comment by yorkerlin** [comment]
@souravsingh 
In the future, could you please first test a PRs at local before sending us the PR?
We should avoid such simple compilation error.

**Comment by karlnapf** [comment]
Indeed

**Comment by souravsingh** [comment]
The tests passed in my local machine. I don't know why it failed here.

**Comment by yorkerlin** [comment]
I do not want to discourage you. 
According to the error log, I do not think you can compile the source code.
Note that:
`falconn::DenseVector<double> temp = Map<VectorXd> (vec, vec.len);`
You should use `vec.vlen` instead of `vec.len`.
  
```
/opt/shogun/src/shogun/multiclass/KNN.cpp: In member function 'virtual shogun::CMulticlassLabels* shogun::CKNN::apply_multiclass(shogun::CFeatures*)':

/opt/shogun/src/shogun/multiclass/KNN.cpp:311:64: error: 'class shogun::SGVector<double>' has no member named 'len'

    falconn::DenseVector<double> temp = Map<VectorXd> (vec, vec.len);

                                                                ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:308:12: warning: unused variable 'len' [-Wunused-variable]

    int32_t len;

            ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:309:9: warning: unused variable 'free' [-Wunused-variable]

    bool free;

         ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:337:64: error: 'class shogun::SGVector<double>' has no member named 'len'

    falconn::DenseVector<double> temp = Map<VectorXd> (vec, vec.len);

                                                                ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:334:12: warning: unused variable 'len' [-Wunused-variable]

    int32_t len;

            ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:335:9: warning: unused variable 'free' [-Wunused-variable]

    bool free;

         ^

make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/multiclass/KNN.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2

make: *** [all] Error 2

The command "docker exec -t devenv /bin/sh -c "cd /opt/shogun/build; make -j2"" exited with 2.

10.19s$ docker exec -t devenv /bin/sh -c "cd /opt/shogun/build; make install"

[  0%] Built target GoogleMock

[  1%] Built target discover_gtest_tests

[  1%] Built target class_list

[  2%] Generating version header

[  2%] Built target version

[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/multiclass/KNN.cpp.o

/opt/shogun/src/shogun/multiclass/KNN.cpp: In member function 'virtual shogun::CMulticlassLabels* shogun::CKNN::apply_multiclass(shogun::CFeatures*)':

/opt/shogun/src/shogun/multiclass/KNN.cpp:311:64: error: 'class shogun::SGVector<double>' has no member named 'len'

    falconn::DenseVector<double> temp = Map<VectorXd> (vec, vec.len);

                                                                ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:308:12: warning: unused variable 'len' [-Wunused-variable]

    int32_t len;

            ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:309:9: warning: unused variable 'free' [-Wunused-variable]

    bool free;

         ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:337:64: error: 'class shogun::SGVector<double>' has no member named 'len'

    falconn::DenseVector<double> temp = Map<VectorXd> (vec, vec.len);

                                                                ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:334:12: warning: unused variable 'len' [-Wunused-variable]

    int32_t len;

            ^

/opt/shogun/src/shogun/multiclass/KNN.cpp:335:9: warning: unused variable 'free' [-Wunused-variable]

    bool free;

         ^

make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/multiclass/KNN.cpp.o] Error 1

make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2

make: *** [all] Error 2
```

**Comment by souravsingh** [comment]
My bad. I made some unwanted changes before pushing

**Pull request closed without merging**
