### PR TITLE
Rename files for meta examples

### PR DESCRIPTION
**Pull request by dgkim5360**
Referring #4050

### CODE REVIEW

**Comment by lisitsyn** [comment]
@dgkim5360 thanks for the PR and welcome!

@karlnapf I think this one is for you

**Comment by karlnapf** [comment]
Great stuff, thanks for the patch!!!
One thing is that the `data` submodule needs to be updated first as I think all integration tests will fail otherwise. Or am I wrong?
Check the developing and examples readme on how to run those tests

**Comment by karlnapf** [comment]
I.e. each meta example generates output of the same filename as itself.
Then the output is compared across the different languages and the c++ version.
Now if you rename the files, our build simply doesnt run the tests anymore (check output of the c++ build)

**Comment by karlnapf** [comment]
See here https://travis-ci.org/shogun-toolbox/shogun/jobs/322523257#L4853

you can see that only the tests for the not-renamed files were executed.
You will need to rename the test files as well, send a PR to the `data` submodule, and then update the submodule version in  this PR here. Then the tests will be executed and we can merge this.
Thanks so much for the effort!

**Comment by dgkim5360** [comment]
I see that's why the number of tests decreased when I renamed the files. I will check the READMEs and tests again, and also the `data` submodule. I appreciate your guides.

**Comment by dgkim5360** [comment]
After checking for renaming in the `data` module to recover the test cases, I have sent a PR to `shogun/shogun-data`. Is this enough, or anything else to do for this PR? Please let me know :)

**Comment by dgkim5360** [comment]
I just recognized I have to update this PR for triggering CI (updating submodule version as you said), but I felt something wrong with the git working flow. Excuse me for taking some time to figure out for clean commits...

**Comment by dgkim5360** [comment]
I am not sure the job is done well. Please tell me if I need to adjust !

**Comment by karlnapf** [comment]
Looks good to me! Thanks a lot for the cleanup

**Comment by dgkim5360** [comment]
This was my first contribution for the open source project. Grateful for such opportunity and experience.

**Comment by karlnapf** [comment]
Well done on that! :)
Feel free to do another one ... always welcome!

**Pull request merged**
