### PR TITLE
Solves issue #5070

### PR DESCRIPTION
**Pull request by yuvraj2701**
Moved fequals and fequals_abs to Fequal.h. I feel "Math::abs", "Math::is_nan" functions also need to be moved so that Fequal.h is completely independent of Math.h.

### CODE REVIEW

**Comment by gf712** [comment]
You can see the error on the CI https://dev.azure.com/shogunml/shogun/_build/results?buildId=4013&view=logs&jobId=be3b03d7-4089-5ab3-9462-9af4d8b1dcdf&j=be3b03d7-4089-5ab3-9462-9af4d8b1dcdf&t=443ade06-68af-54ec-5bea-0e179d048f6f

It seems like you forgot to refactor the math unittest

**Comment by yuvraj2701** [comment]
@gf712 sorry for the previous mistake. I made the required changes but still few tests are failing to which I am not able to find answers online. Could you please help?

**Comment by yuvraj2701** [comment]
There is some issue related to Eigen3
https://dev.azure.com/shogunml/shogun/_build/results?buildId=4014&view=logs&j=f9754876-58be-5644-7278-7cc807306c84&t=174218aa-5153-53fa-666b-4bb48f7a77b4&l=78

**Comment by LiuYuHui** [comment]
> There is some issue related to Eigen3
> https://dev.azure.com/shogunml/shogun/_build/results?buildId=4014&view=logs&j=f9754876-58be-5644-7278-7cc807306c84&t=174218aa-5153-53fa-666b-4bb48f7a77b4&l=78

@yuvraj2701 I think this error is unrelated to your pr, the only thing you need to change is notebooks.

**Comment by yuvraj2701** [comment]
@LiuYuHui can you please tell what changes have to be made?
I don't think changing eigen3 version in CmakeLists.txt as per my system version and then making a PR would be a valid solution. I  am not able to update eigen3 in my system as well.

**Comment by LiuYuHui** [comment]
@yuvraj2701 don't worry about `MacOS ACCELERATE` and `MacOS MKL`, those two ci was broken for a while, you just need to fix [jupyter notebooks](https://dev.azure.com/shogunml/shogun/_build/results?buildId=4014&view=logs&jobId=089c709a-44eb-5f6e-96e7-15e9ee1ff5bf&j=089c709a-44eb-5f6e-96e7-15e9ee1ff5bf&t=2da3e16b-a2b2-5f01-2cbe-a20d9528195b).

**Comment by yuvraj2701** [comment]
ImportError: cannot import name 'Statistics' from 'shogun' (/build/src/interfaces/python/shogun.py)

@LiuYuHui this is one of the errors in jupyter notebook. I have not built the python interface on my system. Is it something related to that?
What can I do to solve this?

**Comment by gf712** [comment]
any updates here?

**Pull request closed without merging**
