### PR TITLE
Fixed typo in error message for gd_momentum range

### PR DESCRIPTION
**Pull request by arasuarun**
A very trivial typo. 
Changed: ">" to ">="

### CODE REVIEW

**Comment by iglesias** [comment]
Thanks!

**Comment by iglesias** [comment]
@yorkerlin, any idea why the unit tests below failed in the clang job of Travis? Have you seen these tests failing other times?

`
The following tests FAILED:
	 48 - unit-GaussianARDKernel (Failed)
	 93 - unit-GaussianProcessClassificationUsingSingleFITCLaplacian (Failed)
	 95 - unit-GaussianProcessRegression (Failed)
	218 - unit-FITCInferenceMethod (Failed)
	228 - unit-SingleFITCLaplacianInferenceMethod (Failed)
	229 - unit-SingleFITCLaplacianInferenceMethodWithLBFGS (Failed)
Errors while running CTest
`

**Comment by yorkerlin** [comment]
I tired to fix this issue. The issue is caused by GaussianARDKernel.
However, it seems the issue is compiler-specific (clang only). I cannot
reproduce the bug in my local Linux machine using gcc and I do not have a
Mac :(

On Thursday, January 21, 2016, Fernando J. Iglesias García <
notifications@github.com> wrote:

> @yorkerlin <https://github.com/yorkerlin>, any idea why the unit tests
> below failed in the clang job of Travis? Have you seen these tests failing
> other times?
>
>
> The following tests FAILED:
> 48 - unit-GaussianARDKernel (Failed)
> 93 - unit-GaussianProcessClassificationUsingSingleFITCLaplacian (Failed)
> 95 - unit-GaussianProcessRegression (Failed)
> 218 - unit-FITCInferenceMethod (Failed)
> 228 - unit-SingleFITCLaplacianInferenceMethod (Failed)
> 229 - unit-SingleFITCLaplacianInferenceMethodWithLBFGS (Failed)
> Errors while running CTest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun/pull/2970#issuecomment-173522874>
> .
>


-- 
best,

wu lin

**Comment by arasuarun** [comment]
Not sure if this will help, but I always get these 6 failing tests, whatever I do. (I have a Macbook)
```
[----------] Global test environment tear-down
[==========] 1164 tests from 254 test cases ran. (6495 ms total)
[  PASSED  ] 1158 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] GaussianProcessClassificationUsingSingleFITCLaplacian.get_mean_vector
[  FAILED  ] GaussianProcessClassificationUsingSingleFITCLaplacian.get_variance_vector
[  FAILED  ] GaussianProcessClassificationUsingSingleFITCLaplacian.get_probabilities
[  FAILED  ] PeriodicKernelTest.test_kernel_matrix
[  FAILED  ] PeriodicKernelTest.test_derivative_width
[  FAILED  ] PeriodicKernelTest.test_derivative_period

 6 FAILED TESTS
  YOU HAVE 5 DISABLED TESTS
```

**Comment by iglesias** [comment]
Hey @yorkerlin. You don't need a mac to use clang ;-) I think clang is the default compiler in os x (don't quote me on this one before double checking) but you can definitely use it in linux as well. 

In fact, the clang job that is failing in Travis is running Ubuntu 12.04.

**Pull request merged**
